import type { Metadata } from "next";
import Link from "next/link";
import InformationPage from "@/components/InformationPage";
import {operator,supportHref} from "@/lib/siteOperator";
export const metadata:Metadata={title:"Information | qatools",robots:{index:false,follow:true}};
export default function StoreInformation(){return <InformationPage title="Information" policy>
<section id="terms"><h2>Terms and license</h2><p>qatools provides digital tools for SideFX Houdini. An account is required. Purchases are one-time payments, processed by Paddle as the reseller under its <a href="https://www.paddle.com/legal/buyer-terms">buyer terms</a>. Check product compatibility before purchasing.</p><p>One account key activates your owned tools on one computer. Activation and renewal require internet access; updated installers support up to seven days offline after successful renewal. A connection failure preserves a still-valid cached license. Contact us to release your previous computer before activating another.</p><p>The website operator is identified in the <Link href="/legal">Legal notice</Link>.</p></section>
<section id="refunds"><h2>Refunds</h2><p>Email <a href={supportHref}>{operator.email}</a> within 14 days of purchase with your order reference and reason. Requests are reviewed individually; approval is not guaranteed. Your statutory consumer rights, including applicable withdrawal and faulty-product remedies, are unaffected. Paddle&apos;s <a href="https://www.paddle.com/legal/refund-policy">refund policy</a> also applies.</p><p>A full refund removes access supplied by that purchase, while preserving access from other valid purchases. Existing offline authorization may remain valid until a successful check or expiry.</p></section>
<section id="privacy"><h2>Privacy</h2><p>The operator named in our <Link href="/legal">Legal notice</Link> uses account/profile information, purchase and refund records, machine/activation identifiers, download requests, security information and support messages to provide and protect the service. Intended legal bases are service performance, legitimate security/support interests and applicable legal obligations.</p><p>Supabase provides authentication and storage, Vercel hosts the website, Resend delivers account email, and Paddle handles payments under its <a href="https://www.paddle.com/legal/privacy">privacy notice</a>. Browser storage keeps sessions, cart and likes; Houdini keeps the local license cache. Provider arrangements, international transfers and retention details are being finalized before live sales.</p><p>Contact us to exercise applicable access, correction, deletion, restriction, portability or objection rights, or withdraw consent where relevant. Required legal records may be retained. You may complain to a competent data protection authority, including Spain&apos;s <a href="https://www.aepd.es">AEPD</a>.</p></section>
<section id="support"><h2>Support</h2><p><a href={supportHref}>{operator.email}</a>. Include your account email, tool name, Houdini version and order reference where relevant. Never send passwords, activation keys or private license files. See <Link href="/install">How to install</Link> for installation help, or <a href="https://paddle.net">Paddle buyer support</a> for payment queries.</p></section>
</InformationPage>;}
