const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,mocks={},globals={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,require:n=>n in mocks?mocks[n]:require(n),console,URL,URLSearchParams,Date,Number,JSON,Map,Set,Promise,...globals});return exports;}
const draft={name:'',product_type:'tool',subtitle:'',description:'',price_eur:0,compatibility:'',current_version:'',release_date:null,category_id:0,complexity_id:0,tool_ids:[]};
function storageHarness(){const text=new Map(),files=new Map();let puts=0,fail=false;const localStorage={getItem:k=>text.get(k)??null,setItem:(k,v)=>text.set(k,v),removeItem:k=>text.delete(k)};
 const indexedDB={open(){const open={};setImmediate(()=>{open.result={close(){},transaction(){const transaction={};const execute=action=>{const request={};setImmediate(()=>{if(fail){transaction.error=new Error('quota');transaction.onerror?.();return;}request.result=action();transaction.oncomplete?.();});return request;};transaction.objectStore=()=>({get:key=>execute(()=>files.get(key)),put:(value,key)=>execute(()=>{puts++;files.set(key,value);return key;}),delete:key=>execute(()=>files.delete(key))});return transaction;}};open.onsuccess?.();});return open;}};
 const library=load('src/lib/adminDraftRecovery.ts',{'./productDraft':load('src/lib/productDraft.ts')},{localStorage,indexedDB});
 const snapshot=(revision='r1')=>({version:1,requestId:'00000000-0000-0000-0000-000000000001',id:null,updatedAt:null,draft,priceText:'',savedAt:'2026-10-05T12:00:00Z',fileRevision:revision,mainFile:null,galleryFiles:[],toolFile:null});return {library,text,files,snapshot,get puts(){return puts;},set fail(v){fail=v;}};
}
test('unfinished text and pending files recover per admin, without rewriting blobs on every keystroke',async()=>{const s=storageHarness(),image={name:'image.gif'},tool={name:'qafit.hda'},gallery={name:'extra.png'};const first={...s.snapshot(),mainFile:image,toolFile:tool,galleryFiles:[gallery]};await s.library.writeDraftRecovery('admin-a',first);assert.equal(await s.library.readDraftRecovery('admin-b'),null);const restored=await s.library.readDraftRecovery('admin-a');assert.equal(restored.mainFile,image);assert.equal(restored.toolFile,tool);assert.equal(restored.galleryFiles[0],gallery);assert.equal(restored.draft.name,'');await s.library.writeDraftRecovery('admin-a',{...first,fileRevision:'r2',draft:{...draft,name:'qatesta01'}});assert.equal(s.puts,1);assert.equal((await s.library.readDraftRecovery('admin-a')).draft.name,'qatesta01');});
test('rapid file changes and deletion cannot resurrect an old recovery',async()=>{const s=storageHarness();const a=s.library.writeDraftRecovery('a',{...s.snapshot(),mainFile:{name:'old.png'}}),b=s.library.writeDraftRecovery('a',{...s.snapshot('r2'),mainFile:{name:'new.png'}});await Promise.all([a,b]);assert.equal((await s.library.readDraftRecovery('a')).mainFile.name,'new.png');const pending=s.library.writeDraftRecovery('a',s.snapshot('r3'));await s.library.clearDraftRecovery('a');await pending;assert.equal(await s.library.readDraftRecovery('a'),null);assert.equal(s.files.has('a'),false);});
test('file storage failures preserve text and expose an actionable recovery warning',async()=>{const s=storageHarness();await s.library.writeDraftRecovery('a',s.snapshot());s.fail=true;await assert.rejects(s.library.writeDraftRecovery('a',{...s.snapshot('r2'),draft:{...draft,name:'keepme'},toolFile:{name:'tool.hda'}}),/quota/);s.fail=false;const restored=await s.library.readDraftRecovery('a');assert.equal(restored.draft.name,'keepme');assert.match(restored.recoveryWarning,/file selections/);assert.equal(restored.toolFile,null);});
test('malformed recovery metadata is ignored rather than submitted as a product',()=>{const s=storageHarness();for(const value of [null,{}, {...s.snapshot(),id:-1},{...s.snapshot(),requestId:'invalid'},{...s.snapshot(),draft:{...draft,tool_ids:[-1]}}])assert.equal(s.library.recoveryMetadata(JSON.stringify(value)),null);assert.ok(s.library.recoveryMetadata(JSON.stringify(s.snapshot())));});
const catalogLib=load('src/lib/adminProductCatalog.ts');
const products=[{...draft,id:30,name:'older',slug:'older',published:true,price_eur:5,category_id:1,complexity_id:1,updated_at:'2026-10-04T12:00:00Z',product_media:[]},{...draft,id:2,name:'newer',slug:'newer',published:false,price_eur:null,updated_at:'2026-10-05T12:00:00Z',product_media:[]},{...draft,id:3,name:'bundle',slug:'bundle',product_type:'bundle',published:false,updated_at:'2026-10-05T10:00:00Z',product_media:[]}];
const catalog={products,categories:[{id:1,name:'sop',active:true}],complexities:[{id:1,name:'easy',active:true}]};
test('catalog filters use OR within each group and AND between groups, with deterministic save-date sorting',()=>{assert.deepEqual(Array.from(catalogLib.catalogProducts(products,[],[],'')).map(p=>p.id),[2,3,30]);assert.equal(products[0].id,30);assert.deepEqual(Array.from(catalogLib.catalogProducts(products,['published','unpublished'],['tool'],'')).map(p=>p.id),[2,30]);assert.deepEqual(Array.from(catalogLib.catalogProducts(products,['unpublished'],['bundle'],'bundle')).map(p=>p.id),[3]);assert.deepEqual(Array.from(catalogLib.productLabels(products[0],catalog)),['sop','easy','tool']);});
function componentHarness(file,mocks={},globals={}){let index=0;const state=[];const react={...require('react'),useState(initial){const i=index++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return [state[i],value=>state[i]=typeof value==='function'?value(state[i]):value];},useRef(initial){const i=index++;if(!(i in state))state[i]={current:initial};return state[i];},useEffect(){index++;}};const component=load(file,{react,...mocks},globals);return props=>{index=0;return component.default(props);};}
function nodes(node){if(!node||typeof node!=='object')return [];if(Array.isArray(node))return node.flatMap(nodes);return [node,...nodes(node.props?.children)];}
function text(node){if(node===null||node===undefined)return '';if(typeof node!=='object')return String(node);if(Array.isArray(node))return node.map(text).join('');return text(node.props?.children);}
test('actual catalog card/list toggle retains filters and presents the requested columns and product actions',()=>{const render=componentHarness('src/components/AdminProductCatalog.tsx',{'@/lib/supabase':{supabase:{}},'@/lib/productDraft':load('src/lib/productDraft.ts'),'@/lib/adminProductCatalog':catalogLib,'./PublicationState':()=>null,'next/image':()=>null});let tree=render({catalog,recovery:null});const articles=nodes(tree).filter(n=>n.type==='article');assert.equal(articles[0].key,'2');assert.ok(nodes(tree).some(n=>n.type==='button'&&text(n)==='Published'&&n.props.disabled));const filter=nodes(tree).find(n=>n.type==='button'&&text(n)==='UNPUBLISHED');filter.props.onClick();tree=render({catalog,recovery:null});assert.equal(nodes(tree).filter(n=>n.type==='article').length,2);nodes(tree).find(n=>n.type==='button'&&text(n)==='List view').props.onClick();tree=render({catalog,recovery:null});assert.deepEqual(nodes(tree).filter(n=>n.type==='th').map(text),['Image','Name','Price','Tags','State','Last saved','Actions']);assert.equal(nodes(tree).filter(n=>n.type==='tr'&&n.key).length,2);});
test('HDA picker is available before saving; upload resolves a real draft and retains the file on failure',async()=>{
 for(const failed of [false,true]){
  let kept=new File(['INDXtest'],'tool.hda'),ensured=0;const calls=[];
  const render=componentHarness('src/components/AdminToolPackage.tsx',{'@/lib/supabase':{supabase:{auth:{getSession:async()=>({data:{session:{access_token:'test'}},error:null})}}}},{FormData,URLSearchParams,fetch:async(url,options)=>{calls.push({url,options});return url.startsWith('/api/admin/downloads')?Response.json({download:null}):Response.json(failed?{error:'Upload failed'}:{download:{file_name:'tool.zip',file_path:'7/tool.zip',enabled:true},message:'Saved'},{status:failed?503:200});}});
  const props={productId:null,disabled:false,tool:kept,onToolChange:file=>kept=file,ensureDraft:async()=>{ensured++;return 7;},onBusyChange:()=>{}};
  const tree=render(props);assert.equal(nodes(tree).find(n=>n.type==='fieldset').props.disabled,false);const button=nodes(tree).find(n=>n.type==='button'&&text(n)==='Upload & prepare installer');assert.equal(button.props.disabled,false);await button.props.onClick();assert.equal(ensured,1);assert.equal(calls.length,2);assert.match(calls[1].url,/productId=7/);assert.equal(kept===null,!failed);
 }
});

function workflowHarness(mocks,globals){let cursor=0,changed=true;const values=[],dependencies=[],effects=[];const react={...require('react'),useState(initial){const i=cursor++;if(!(i in values))values[i]=initial;return [values[i],v=>{const next=typeof v==='function'?v(values[i]):v;if(next!==values[i])changed=true;values[i]=next;}];},useRef(initial){const i=cursor++;if(!(i in values))values[i]={current:initial};return values[i];},useEffect(fn,deps){const i=cursor++;if(!dependencies[i]||deps.some((d,j)=>d!==dependencies[i][j])){dependencies[i]=deps;effects.push(fn);}}};const Component=load('src/components/AdminProducts.tsx',{react,'./AdminProducts.css':{},'@/components/AdminPrices':{},'@/components/ProductPublication':{},'@/components/AdminDownloads':{},'@/components/AdminToolPackage':{},'@/components/PublicationState':{},'./AdminProductCatalog':{},'next/image':{},'next/navigation':{useRouter:()=>({push:()=>{}})},'@/context/AuthContext':{useAuth:()=>({user:{id:'admin-a'},loading:false})},'@/lib/productDraft':load('src/lib/productDraft.ts'),...mocks},globals).default;let tree;
 return {async settle(){for(let i=0;i<12;i++){if(changed){changed=false;cursor=0;tree=Component({editor:true});}while(effects.length)effects.shift()();await new Promise(resolve=>setImmediate(resolve));if(!changed&&!effects.length)break;}return tree;},get tree(){return tree;}};
}
test('resuming after a lost creation response updates the existing draft with the latest edits',async()=>{
 const record={...products[1],id:9,name:'old-name',slug:'old-name',updated_at:'2026-10-05T09:00:00Z'};let stored=record;const requests=[];const snapshot={...storageHarness().snapshot(),draft:{...draft,name:'latest-name'}};
 const h=workflowHarness({'@/lib/supabase':{supabase:{auth:{getSession:async()=>({data:{session:{access_token:'test'}},error:null})}}},'@/lib/adminDraftRecovery':{readDraftRecovery:async()=>snapshot,writeDraftRecovery:async()=>{},clearDraftRecovery:async()=>{}}},{crypto:require('node:crypto').webcrypto,window:{location:{search:'?resume=1'},history:{replaceState(){}},addEventListener(){},removeEventListener(){}},fetch:async(url,options={})=>{if(options.method==='POST'){const body=JSON.parse(options.body);requests.push(body);if(body.productId)stored={...stored,...body.data,name:body.data.name,slug:body.data.name,updated_at:'2026-10-05T12:00:00Z'};return Response.json({draft:{id:9,updated_at:stored.updated_at},message:'Saved'});}return Response.json({products:[stored],categories:[],complexities:[]});}});
 await h.settle();await nodes(h.tree).find(n=>n.type==='form').props.onSubmit({preventDefault(){}});await h.settle();assert.equal(requests.length,2);assert.equal(requests[0].productId,undefined);assert.equal(requests[1].productId,9);assert.equal(requests[1].expectedUpdatedAt,record.updated_at);assert.equal(stored.name,'latest-name');
});
test('failed new-product media upload keeps its selected file and unpublished draft for retry',async()=>{
 const file=new File(['image'],'gallery.png',{type:'image/png'});const snapshot={...storageHarness().snapshot(),draft:{...draft,name:'new-tool'},galleryFiles:[file]};let stored=null;const uploads=[];
 const h=workflowHarness({'@/lib/supabase':{supabase:{auth:{getSession:async()=>({data:{session:{access_token:'test'}},error:null})}}},'@/lib/adminDraftRecovery':{readDraftRecovery:async()=>snapshot,writeDraftRecovery:async()=>{},clearDraftRecovery:async()=>{}}},{crypto:require('node:crypto').webcrypto,window:{location:{search:'?resume=1'},history:{replaceState(){}},addEventListener(){},removeEventListener(){}},URLSearchParams,fetch:async(url,options={})=>{if(options.method==='POST' && url.startsWith('/api/admin/products/media')){uploads.push(url);return Response.json({error:'Image upload failed'},{status:503});}if(options.method==='POST'){const body=JSON.parse(options.body);stored={...body.data,id:9,slug:body.data.name,published:false,product_media:[],updated_at:'2026-10-05T12:00:00Z'};return Response.json({draft:{id:9,updated_at:stored.updated_at},message:'Saved'});}return Response.json({products:stored?[stored]:[],categories:[],complexities:[]});}});
 await h.settle();await nodes(h.tree).find(n=>n.type==='form').props.onSubmit({preventDefault(){}});await h.settle();assert.equal(uploads.length,1);assert.equal(stored.published,false);assert.ok(text(h.tree).includes('gallery.png'));assert.ok(text(h.tree).includes('Image upload failed'));
});
