const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const stamp='2026-10-08T12:00:00Z',priceId='pri_'+'a'.repeat(26),productId='pro_'+'b'.repeat(26);
function setup(options={}){const calls=[],network=[],cache=new Map(),environment=options.environment??'live';
 const db={from(table){calls.push({table});const q={select(){return q;},eq(){return q;},maybeSingle:async()=>({error:null,data:table==='products'?{id:2,slug:'synthetic',price_eur:7,published:false,updated_at:stamp}:options.noPrice?null:{product_id:2,price_id:priceId,paddle_product_id:productId,enabled:true}})};return q;},rpc:async(name,args)=>{calls.push({name,args});return {data:name.includes('checks')?{ready:!options.missing,missing:options.missing?['Verified Paddle price']:[],updated_at:stamp}:{id:2,updated_at:stamp},error:null};}};
 function load(file){if(cache.has(file))return cache.get(file);const mod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:mod.exports,URL,Date,Number,Buffer,Request,Response,AbortSignal,process:{env:{PADDLE_ENVIRONMENT:environment,PADDLE_LIVE_API_KEY:'pdl_live_apikey_synthetic',PADDLE_API_KEY:'pdl_sdbx_apikey_synthetic'}},fetch:async(url,config)=>{network.push({url,config});return {ok:true,json:async()=>({data:{id:priceId,product_id:productId,type:'standard',status:'active',billing_cycle:null,trial_period:null,tax_mode:'internal',unit_price:{amount:options.priceMismatch?'800':'700',currency_code:'EUR'},quantity:{minimum:1,maximum:1},unit_price_overrides:[],product:{id:productId,name:'synthetic',status:'active',tax_category:'standard'}}})};},require(n){if(n==='server-only')return {};if(n==='next/server')return {NextResponse:{json:(v,init={})=>Response.json(v,init)}};if(n==='@/lib/requireAdmin')return {requireAdmin:async()=>options.denied?{response:Response.json({error:'denied'},{status:403})}:{user:{id:'trusted-admin'}}};if(n==='@/lib/paddleCartDatabase'||n==='./paddleCartDatabase')return {paddleCartDatabase:db};if(n==='@/lib/supabaseAdmin')return {supabaseAdmin:db};if(n.startsWith('@/lib/'))return load('src/lib/'+n.slice(6)+'.ts');if(n.startsWith('./'))return load('src/lib/'+n.slice(2)+'.ts');throw Error(n);}});cache.set(file,mod.exports);return mod.exports;}
 return {calls,network,get:()=>load('src/app/api/admin/products/readiness/route.ts').GET(new Request('https://www.qatools.org/api/admin/products/readiness?productId=2')),publish:(expectedEnvironment=environment)=>load('src/app/api/admin/products/route.ts').PATCH(new Request('https://www.qatools.org/api/admin/products',{method:'PATCH',body:JSON.stringify({productId:2,expectedUpdatedAt:stamp,expectedEnvironment})}))};
}
test('live readiness and publication require live mapping and reverify its remote price',async()=>{const s=setup(),r=await s.get();assert.equal(r.status,200);assert.equal((await r.json()).environment,'live');assert.equal((await s.publish()).status,200);assert.ok(s.calls.some(c=>c.name==='live_product_publication_checks'));assert.ok(s.calls.some(c=>c.name==='publish_live_product_draft'&&c.args.p_expected_price_id===priceId&&c.args.p_admin_id==='trusted-admin'));assert.ok(s.calls.some(c=>c.table==='live_product_prices'));assert.ok(s.network.every(n=>n.url.startsWith('https://api.paddle.com/')));});
test('live publication refuses missing/mismatched prices and stale loaded environment',async()=>{for(const options of [{missing:true},{noPrice:true},{priceMismatch:true}]){const s=setup(options);assert.ok((await s.publish()).status>=400);assert.ok(!s.calls.some(c=>c.name==='publish_live_product_draft'));}const stale=setup();assert.equal((await stale.publish('sandbox')).status,409);assert.equal(stale.calls.length,0);assert.equal(stale.network.length,0);});
test('live publishing and readiness independently require admin authorization',async()=>{const s=setup({denied:true});assert.equal((await s.get()).status,403);assert.equal((await s.publish()).status,403);assert.equal(s.calls.length,0);assert.equal(s.network.length,0);});
