const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),crypto=require('node:crypto');
const id=(prefix,n=1)=>prefix+'_'+String(n).padStart(26,'0'),intent='00000000-0000-4000-8000-000000000001';
function fixture(){const price={id:id('pri'),product_id:id('pro'),billing_cycle:null,trial_period:null,tax_mode:'internal',unit_price:{amount:'500',currency_code:'EUR'}};return {event_id:id('evt'),event_type:'transaction.completed',occurred_at:'2026-10-08T12:00:00Z',data:{id:id('txn'),status:'completed',collection_mode:'automatic',currency_code:'EUR',subscription_id:null,discount_id:null,custom_data:{qatools_environment:'live',qatools_checkout_id:intent,qatools_checkout_version:'cart-v1'},items:[{quantity:1,price}],details:{totals:{subtotal:'417',tax:'83',total:'500',grand_total:'500',currency_code:'EUR',discount:'0',credit:'0',credit_to_balance:'0',balance:'0'},line_items:[{id:id('txnitm'),price_id:price.id,quantity:1,product:{id:price.product_id},totals:{total:'500',discount:'0'}}]}}};}
function setup(options={}){const calls=[],cache=new Map(),env={PADDLE_ENVIRONMENT:'sandbox',PADDLE_LIVE_WEBHOOK_SECRET:options.noSecret?'':'live-synthetic-secret',PADDLE_SANDBOX_WEBHOOK_SECRET:'sandbox-synthetic-secret'};
 function load(file){if(cache.has(file))return cache.get(file);const mod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:mod.exports,Buffer,Date,Request,Response,process:{env},require(name){if(name==='server-only')return {};if(name==='node:crypto')return crypto;if(name==='next/server')return {NextResponse:{json:Response.json}};if(name==='@/lib/paddleWebhookDatabase')return {paddleLiveWebhookDatabase:{rpc:async(name,args)=>{calls.push({name,args});return {data:{ok:!options.retry},error:options.dbError?{}:null};}}};if(name.startsWith('@/lib/'))return load('src/lib/'+name.slice(6)+'.ts');if(name==='./paddleCartValidation')return load('src/lib/paddleCartValidation.ts');throw Error(name);}});cache.set(file,mod.exports);return mod.exports;}
 return {calls,load,post(event=fixture(),secret='live-synthetic-secret'){const raw=JSON.stringify(event),time=Math.floor(Date.now()/1000),signature=crypto.createHmac('sha256',secret).update(time+':'+raw).digest('hex');return load('src/app/api/paddle/webhook/live/route.ts').POST(new Request('https://www.qatools.org/api/paddle/webhook/live',{method:'POST',body:raw,headers:{'paddle-signature':`ts=${time};h1=${signature}`}}));}};
}
test('live signature uses its own secret while active checkout remains sandbox',async()=>{const s=setup();assert.equal((await s.post()).status,200);assert.equal(s.calls[0].name,'process_live_payment_event');assert.equal(s.calls[0].args.p_event.environment,'live');assert.equal(s.calls[0].args.p_event.valid,true);const bad=setup();assert.equal((await bad.post(fixture(),'sandbox-synthetic-secret')).status,400);assert.equal(bad.calls.length,0);});
test('live normalization refuses sandbox attribution, legacy payment, simulations and tampering',()=>{const normalize=setup().load('src/lib/paddleFulfillment.ts').normalizePaddleEvent;assert.equal(normalize(fixture(),'live').valid,true);assert.equal(normalize(fixture(),'sandbox').valid,false);for(const modify of [e=>e.data.custom_data.qatools_environment='sandbox',e=>delete e.data.custom_data.qatools_checkout_version,e=>e.event_id=id('ntfsimevt'),e=>e.data.details.totals.total='499',e=>e.data.items[0].quantity=2]){const e=fixture();modify(e);assert.equal(normalize(e,'live').valid,false);}});
test('live route retries configuration and database failures without exposing secrets',async()=>{for(const flag of ['noSecret','dbError','retry']){const s=setup({[flag]:true}),r=await s.post();assert.equal(r.status,503);assert.equal((await r.text()).includes('synthetic-secret'),false);if(flag==='noSecret')assert.equal(s.calls.length,0);}});
test('live delivery normalizes approved refunds and stores no customer personal payload',async()=>{const s=setup(),e=fixture();e.data.customer={email:'private@example.invalid'};e.data.address={street:'Private street'};await s.post(e);assert.ok(!JSON.stringify(s.calls).includes('private@'));assert.ok(!JSON.stringify(s.calls).includes('Private street'));const refund={event_id:id('evt',2),event_type:'adjustment.updated',occurred_at:e.occurred_at,data:{id:id('adj'),transaction_id:id('txn'),action:'refund',type:'full',status:'approved',currency_code:'EUR',subscription_id:null,totals:{total:'500',currency_code:'EUR'}}};await s.post(refund);assert.equal(s.calls[1].args.p_event.fullRefund,true);assert.equal(s.calls[1].args.p_event.environment,'live');});
