const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const {createRequire}=require('node:module');const repo=process.env.QATOOLS_TEST_REPO||process.cwd(),stage=process.env.QATOOLS_CART_STAGE||repo,ts=createRequire(path.join(repo,'package.json'))('typescript');
const user='00000000-0000-4000-8000-000000000001',intent='00000000-0000-4000-8000-000000000002',txn='txn_'+'a'.repeat(26),pri='pri_01m41bkp4f0fxgb9cfm37n5p4b',pro='pro_01m41bf7cprd18e5aebzyp1rzw';
const items=[{productId:1,slug:'qafit01',priceId:pri,paddleProductId:pro,amount:500},{productId:2,slug:'synthetic-tool',priceId:'pri_'+'b'.repeat(26),paddleProductId:'pro_'+'b'.repeat(26),amount:700}];
const mapping=items.map(i=>({product_id:i.productId,price_id:i.priceId,paddle_product_id:i.paddleProductId,enabled:true}));
function transaction(paid=false){return {id:txn,status:paid?'completed':'ready',collection_mode:'automatic',currency_code:'EUR',subscription_id:null,discount_id:null,custom_data:{qatools_checkout_id:intent,qatools_environment:'sandbox',qatools_checkout_version:'cart-v1'},items:items.map(i=>({quantity:1,price:{id:i.priceId,product_id:i.paddleProductId,billing_cycle:null,trial_period:null,tax_mode:'internal',unit_price:{amount:String(i.amount),currency_code:'EUR'}}})),details:{totals:{subtotal:'1000',tax:'200',total:'1200',grand_total:'1200',currency_code:'EUR',discount:'0',credit:'0',credit_to_balance:'0',balance:paid?'0':'1200'},line_items:items.map((i,n)=>({id:'txnitm_'+String(n+1).padStart(26,'0'),price_id:i.priceId,quantity:1,product:{id:i.paddleProductId},totals:{total:String(i.amount),discount:'0'}}))}};}
function fixture(n=1){return {event_id:'evt_'+String(n).padStart(26,'0'),event_type:'transaction.completed',occurred_at:'2026-10-04T18:00:00Z',data:transaction(true)};}
function setup(opts={}){
 const calls=[],network=[],cache=new Map();
 const db={from(table){calls.push({table});const filters={};const q={select(columns){calls.push({columns});return q;},eq(k,v){filters[k]=v;calls.push({k,v});return q;},async in(k,ids){return {data:items.filter(i=>ids.includes(i.productId)).map(i=>({id:i.productId,slug:i.slug,price_eur:i.amount/100,published:true})),error:opts.dbError?{}:null};},async maybeSingle(){return {data:table==='admin_users'?(opts.nonAdmin?null:{user_id:user}):{id:1,slug:'qafit01',price_eur:5,published:true},error:opts.membershipError?{}:null};},then(resolve,reject){return Promise.resolve({data:opts.unmapped?[]:mapping,error:opts.dbError?{}:null}).then(resolve,reject);}};return q;},async rpc(name,args){calls.push({name,args});if(opts.rpcError)return {data:null,error:{}};if(name==='reserve_sandbox_cart')return {data:opts.reservation??{ok:true,created:true,intent:{id:intent,status:'creating',snapshot:items,version:'cart-v1'}},error:null};return {data:name==='finish_sandbox_checkout'? !opts.bindError:{ok:!opts.casError},error:null};}};
 function load(file){if(cache.has(file))return cache.get(file);const mod={exports:{}};const target=fs.existsSync(path.join(stage,file))?path.join(stage,file):path.join(repo,file);
  vm.runInNewContext(ts.transpileModule(fs.readFileSync(target,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:mod.exports,URL,Date,AbortSignal,Buffer,process:{env:{PADDLE_SANDBOX_CHECKOUT_ENABLED:opts.disabled?'':'true',NEXT_PUBLIC_SUPABASE_URL:'https://example.invalid',NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:'synthetic'}},fetch:async(url,config)=>{network.push({url,config});if(opts.providerError)throw Error('private transport');if(url.includes('/prices/')){const i=items.find(i=>url.includes(i.priceId));return {ok:!opts.httpError,json:async()=>({data:{id:i.priceId,product_id:i.paddleProductId,status:'active',type:'standard',billing_cycle:null,trial_period:null,tax_mode:opts.taxMismatch?'external':'internal',unit_price:{amount:String(i.amount),currency_code:'EUR'},quantity:{minimum:1,maximum:1},unit_price_overrides:[],product:{id:i.paddleProductId,name:i.slug,status:'active',tax_category:'standard'}}})};}return {ok:!opts.httpError,json:async()=>({data:transaction()})};},require(name){if(name==='server-only')return {};if(name==='next/server')return {NextResponse:{json:Response.json}};if(name==='@/lib/supabaseAdmin')return {supabaseAdmin:db};if(name==='@/lib/paddleCartDatabase')return {paddleCartDatabase:db};if(name==='@/lib/paddleCheckoutDatabase')return {paddleCheckoutDatabase:db};if(name==='./paddleCartDatabase')return {paddleCartDatabase:db};if(name==='@/lib/paddleSandbox'||name==='./paddleSandbox')return {paddleSandboxConfig:()=>({clientToken:'test_synthetic'}),paddleSandboxApiConfig:()=>({apiBase:'https://sandbox-api.paddle.com',apiKey:'synthetic-private'})};if(name==='@supabase/supabase-js')return {createClient:()=>({auth:{getUser:async()=>({data:{user:opts.invalidToken?null:{id:user,email_confirmed_at:opts.unconfirmed?null:'confirmed'}},error:null})}})};if(name.startsWith('@/lib/'))return load('src/lib/'+name.slice(6)+'.ts');if(name.startsWith('./'))return load('src/lib/'+name.slice(2)+'.ts');throw Error(name);}});cache.set(file,mod.exports);return mod.exports;}
 function request(body){return new Request('http://localhost/api/test',{method:'POST',headers:opts.noToken?{}:{Authorization:'Bearer synthetic'},body:JSON.stringify(body)});}
 return {load,calls,network,post(body={productIds:[1,2]}){return load('src/app/api/account/cart-checkout/route.ts').POST(request(body));},admin(body={productId:1,priceId:pri,paddleProductId:pro,enabled:true,expectedPrice:pri,expectedEnabled:true}){return load('src/app/api/admin/prices/route.ts').POST(request(body));}};
}
test('cart validates every line and ignores provider item ordering',()=>{const v=setup().load('src/lib/paddleCartValidation.ts').validateCartTransaction;assert.equal(v(transaction(),intent,items).total,1200);const t=transaction();t.items.reverse();t.details.line_items.reverse();assert.equal(v(t,intent,items).total,1200);});
test('cart rejects missing, duplicate, substituted, discounted, recurring and changed-price lines',()=>{const v=setup().load('src/lib/paddleCartValidation.ts').validateCartTransaction;for(const change of [t=>t.items.pop(),t=>t.items[1]=t.items[0],t=>t.items[1].quantity=2,t=>t.items[1].price.id='pri_'+'c'.repeat(26),t=>t.items[1].price.billing_cycle={},t=>t.items[1].price.tax_mode='external',t=>t.details.line_items[1].id=t.details.line_items[0].id,t=>t.details.line_items[1].totals.total='699',t=>t.details.totals.tax='199',t=>t.details.totals.discount='1',t=>t.details.totals.credit='1',t=>t.details.totals.balance='0',t=>t.custom_data.qatools_environment='live',t=>t.custom_data.qatools_checkout_id='bad',t=>t.currency_code='USD']){const t=transaction();change(t);assert.throws(()=>v(t,intent,items));}});
test('signed multi-item completion is normalized without customer data',()=>{const normalize=setup().load('src/lib/paddleFulfillment.ts').normalizePaddleEvent,e=fixture();e.data.email='private@example.invalid';const n=normalize(e);assert.equal(n.valid,true);assert.equal(n.total,1200);assert.equal(n.items.length,2);assert.equal(n.checkoutVersion,'cart-v1');assert.ok(!JSON.stringify(n).includes('private@'));e.data.items.pop();assert.equal(normalize(e).valid,false);});
test('cart simulations cannot grant ownership',()=>{const normalize=setup().load('src/lib/paddleFulfillment.ts').normalizePaddleEvent,e=fixture();e.event_id='ntfsimevt_'+'a'.repeat(26);const n=normalize(e);assert.equal(n.valid,false);assert.equal(n.txnId,null);assert.equal(n.intentId,null);});
test('business details and zero tax preserve validation without leaking billing data',()=>{
 const s=setup(),validate=s.load('src/lib/paddleCartValidation.ts').validateCartTransaction,normalize=s.load('src/lib/paddleFulfillment.ts').normalizePaddleEvent;
 const t=transaction();t.business_id='biz_'+'c'.repeat(26);t.details.totals.subtotal='1200';t.details.totals.tax='0';
 assert.equal(validate(t,intent,items).total,1200);
 const e=fixture(40);e.data.business_id=t.business_id;e.data.details.totals.subtotal='1200';e.data.details.totals.tax='0';
 e.data.business={name:'Synthetic private company',tax_identifier:'SYNTHETIC-NOT-A-REAL-VAT-ID'};
 const n=normalize(e);assert.equal(n.valid,true);assert.equal(n.total,1200);assert.equal(n.subtotal,1200);assert.ok(!JSON.stringify(n).includes('Synthetic private'));assert.ok(!JSON.stringify(n).includes('SYNTHETIC-NOT'));
 t.details.totals.total='1000';assert.throws(()=>validate(t,intent,items));
});
for(const [option,status] of [['noToken',401],['invalidToken',401],['unconfirmed',403],['disabled',503]])test('cart authentication gate: '+option,async()=>{const s=setup({[option]:true});assert.equal((await s.post()).status,status);assert.equal(s.network.length,0);assert.equal(s.calls.length,0);});
test('cart refuses identity/amount claims, duplicates, empty and oversized carts',async()=>{for(const body of [{productIds:[]},{productIds:[1,1]},{productIds:['1']},{productIds:[0]},{productIds:[1],userId:'forged'},{productIds:[1],total:1},{productIds:Array.from({length:21},(_,i)=>i+1)}]){const s=setup();assert.equal((await s.post(body)).status,400);assert.equal(s.network.length,0);}});
test('cart creates exactly one attributed transaction after trusted reservation and revalidation',async()=>{const s=setup(),r=await s.post(),b=await r.json();assert.equal(r.status,200);assert.equal(b.expected.total,12);assert.equal(b.expected.items.length,2);assert.equal(r.headers.get('cache-control'),'no-store');const posts=s.network.filter(n=>n.config.method==='POST');assert.equal(posts.length,1);const p=JSON.parse(posts[0].config.body);assert.equal(p.items.length,2);assert.ok(p.items.every(i=>i.quantity===1));assert.equal(p.custom_data.qatools_checkout_version,'cart-v1');assert.ok(!JSON.stringify(p).includes(user));assert.ok(s.calls.some(c=>c.name==='reserve_sandbox_cart'&&c.args.p_user_id===user));});
test('blocked and ambiguous carts never issue another provider POST',async()=>{for(const reservation of [{ok:false},{ok:true,created:false,intent:{id:intent,status:'unknown',snapshot:items,version:'cart-v1'}},{ok:true,created:false,intent:{id:intent,status:'creating',snapshot:items,version:'cart-v1'}}]){const s=setup({reservation});assert.equal((await s.post()).status,409);assert.equal(s.network.filter(n=>n.config.method==='POST').length,0);}const s=setup({reservation:{ok:true,created:false,intent:{id:intent,status:'ready',transaction_id:txn,snapshot:items,version:'cart-v1'}}});assert.equal((await s.post()).status,200);assert.equal(s.network.filter(n=>n.config.method==='POST').length,0);});
test('unmapped and mismatched prices fail before reservation',async()=>{for(const option of ['unmapped','taxMismatch']){const s=setup({[option]:true});assert.equal((await s.post()).status,503);assert.ok(!s.calls.some(c=>c.name==='reserve_sandbox_cart'));}});
test('binding failure retains unknown intent without automatic retry or private errors',async()=>{const s=setup({bindError:true}),r=await s.post();assert.equal(r.status,503);assert.equal(s.network.filter(n=>n.config.method==='POST').length,1);assert.equal(s.calls.at(-1).args.p_transaction_id,null);assert.ok(!(await r.text()).includes('private'));});
for(const [option,status] of [['noToken',401],['invalidToken',401],['nonAdmin',403],['membershipError',500]])test('price administration gate: '+option,async()=>{const s=setup({[option]:true});assert.equal((await s.admin()).status,status);assert.equal(s.network.length,0);assert.ok(!s.calls.some(c=>c.name==='set_sandbox_product_price'));});
test('admin mapping validates remote price and passes verified admin identity and CAS state',async()=>{const s=setup();assert.equal((await s.admin()).status,200);assert.ok(s.calls.some(c=>c.name==='set_sandbox_product_price'&&c.args.p_admin_id===user&&c.args.p_expected_price===pri));assert.equal((await setup({taxMismatch:true}).admin()).status,409);assert.equal((await setup({casError:true}).admin()).status,409);});
test('browser checks the entire expected cart rather than just its total',()=>{const check=setup().load('src/lib/paddleBrowser.ts').checkoutMatchesExpectedPrice;const expected={total:12,items:items.map(i=>({priceId:i.priceId,slug:i.slug}))};const e={data:{transaction_id:txn,currency_code:'EUR',totals:{total:12,discount:0,credit:0},items:items.map(i=>({price_id:i.priceId,quantity:1}))}};assert.equal(check(e,txn,expected),true);e.data.items[1].price_id=pri;assert.equal(check(e,txn,expected),false);});
test('SQL cart migration, atomic fulfillment, refunds, rollback and legacy compatibility',async()=>{
 assert.ok(process.env.PGLITE_TEST_MODULE,'Set PGLITE_TEST_MODULE to the isolated PGlite package; SQL verification is mandatory.');
 const {PGlite}=require(process.env.PGLITE_TEST_MODULE),db=new PGlite(),normal=setup().load('src/lib/paddleFulfillment.ts').normalizePaddleEvent;
 const read=f=>fs.readFileSync(fs.existsSync(path.join(stage,f))?path.join(stage,f):path.join(repo,f),'utf8');
 try{
 await db.exec('CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY,email_confirmed_at timestamptz,banned_until timestamptz);CREATE TABLE public.admin_users(user_id uuid PRIMARY KEY REFERENCES auth.users);CREATE TABLE public.products(id bigint PRIMARY KEY,slug text,published boolean,price_eur numeric);CREATE TABLE public.orders(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,user_id uuid REFERENCES auth.users,provider text,provider_transaction_id text UNIQUE,status text CHECK(status IN (\'pending\',\'paid\',\'refunded\',\'partially_refunded\',\'cancelled\')),currency text,subtotal numeric(12,2),total numeric(12,2),provider_created_at timestamptz,created_at timestamptz DEFAULT now());CREATE TABLE public.order_items(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,order_id bigint REFERENCES public.orders,product_id bigint REFERENCES public.products,quantity int CHECK(quantity>0),unit_price numeric(12,2));CREATE TABLE public.entitlements(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,user_id uuid REFERENCES auth.users,product_id bigint REFERENCES public.products,order_item_id bigint REFERENCES public.order_items,source text CHECK(source IN (\'purchase\',\'free\',\'admin\')),status text CHECK(status IN (\'active\',\'refunded\',\'revoked\')),UNIQUE(user_id,product_id));');
 await db.query('INSERT INTO auth.users VALUES($1,now(),null)',[user]);await db.query('INSERT INTO public.admin_users VALUES($1)',[user]);await db.exec("INSERT INTO public.products VALUES(1,'qafit01',true,5),(2,'synthetic-tool',true,7),(3,'unrelated',true,3)");
 for(const file of ['20261003080000_sandbox_checkout_intents.sql','20261003090000_sandbox_payment_fulfillment.sql','20261004100000_paddle_simulation_isolation.sql','20261004120000_customer_order_numbers.sql','20261004130000_sandbox_full_refunds.sql','20261004140000_recheck_approved_refund_events.sql','20261004150000_paddle_replay_event_identity.sql','20261004180000_sandbox_cart_checkout.sql','20261004180100_sandbox_cart_fulfillment.sql','20261004190000_admin_paddle_catalog_setup.sql'])await db.exec(read('supabase/migrations/'+file));
 await db.query('INSERT INTO public.sandbox_product_prices VALUES(2,$1,$2,true)',[items[1].priceId,items[1].paddleProductId]);
 for(const role of ['anon','authenticated','service_role']){const r=(await db.query("SELECT has_function_privilege($1,'public.reserve_sandbox_cart(uuid,jsonb)','EXECUTE') AS execute,has_table_privilege($1,'public.sandbox_product_prices','INSERT,UPDATE,DELETE,TRUNCATE') AS writes",[role])).rows[0];assert.equal(r.execute,role==='service_role');assert.equal(r.writes,false);}
 async function reserve(lines=items){return (await db.query('SELECT public.reserve_sandbox_cart($1,$2::jsonb) AS r',[user,JSON.stringify(lines)])).rows[0].r;}
 await db.query("UPDATE auth.users SET banned_until=now()+interval '1 hour' WHERE id=$1",[user]);assert.equal((await reserve()).ok,false);await db.query('UPDATE auth.users SET banned_until=null WHERE id=$1',[user]);assert.equal((await reserve([items[0],items[0]])).ok,false);
 const altered=JSON.parse(JSON.stringify(items));altered[1].amount=1;assert.equal((await reserve(altered)).ok,false);
 const reserved=await reserve();assert.equal(reserved.created,true);assert.equal((await reserve()).created,false);assert.equal((await reserve([items[1]])).ok,false);
 assert.equal((await db.query('SELECT public.reserve_sandbox_checkout($1,1) AS r',[user])).rows[0].r.ok,false);
 const saved=reserved.intent.id;await db.query('SELECT public.finish_sandbox_checkout($1,$2,$3)',[user,saved,txn]);
 async function process(e){const normalized=normal(e);normalized.eventHash=crypto.createHash('sha256').update(JSON.stringify({...e,notification_id:undefined})).digest('hex');return (await db.query('SELECT public.process_sandbox_payment_event($1::jsonb,$2) AS r',[JSON.stringify(normalized),crypto.createHash('sha256').update(JSON.stringify(e)).digest('hex')])).rows[0].r;}
 const e=fixture();e.data.custom_data.qatools_checkout_id=saved;
 // A forced failure on the second entitlement proves all first-item and order writes roll back.
 await db.exec("CREATE FUNCTION public.force_test_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.product_id=2 THEN RAISE EXCEPTION 'forced rollback'; END IF; RETURN NEW; END $$;CREATE TRIGGER force_test_failure BEFORE INSERT ON public.entitlements FOR EACH ROW EXECUTE FUNCTION public.force_test_failure();");
 await assert.rejects(process(e),/forced rollback/);assert.equal((await db.query('SELECT count(*) AS n FROM public.orders')).rows[0].n,0);assert.equal((await db.query('SELECT count(*) AS n FROM public.entitlements')).rows[0].n,0);assert.equal((await db.query("SELECT last_number FROM public.order_number_counters WHERE scope='sandbox'")).rows[0].last_number,0);await db.exec('DROP TRIGGER force_test_failure ON public.entitlements');
 assert.equal((await process(e)).outcome,'fulfilled');assert.equal((await db.query('SELECT count(*) AS n FROM public.entitlements')).rows[0].n,2);assert.equal((await db.query('SELECT count(*) AS n FROM public.order_items')).rows[0].n,2);assert.equal((await process(e)).outcome,'fulfilled');const dup=JSON.parse(JSON.stringify(e));dup.event_id='evt_'+String(2).padStart(26,'0');assert.equal((await process(dup)).outcome,'duplicate');
 const ref=(await db.query('SELECT order_number FROM public.orders')).rows[0].order_number;assert.ok(ref.startsWith('sandbox-'));
 await db.query("INSERT INTO public.entitlements(user_id,product_id,source,status) VALUES($1,3,'admin','active')",[user]);
 const refund={event_id:'evt_'+String(30).padStart(26,'0'),event_type:'adjustment.updated',occurred_at:'2026-10-04T18:01:00Z',data:{id:'adj_'+'a'.repeat(26),transaction_id:txn,action:'refund',status:'approved',type:'partial',currency_code:'EUR',subscription_id:null,totals:{total:'500',currency_code:'EUR'},items:[{item_id:'txnitm_'+String(1).padStart(26,'0'),type:'full',totals:{total:'500'}}]}};
 assert.equal((await process(refund)).outcome,'refunded');assert.equal((await db.query('SELECT status FROM public.entitlements WHERE product_id=1')).rows[0].status,'refunded');assert.equal((await db.query('SELECT status FROM public.entitlements WHERE product_id=2')).rows[0].status,'active');assert.equal((await db.query('SELECT status FROM public.orders')).rows[0].status,'partially_refunded');
 const wrong=JSON.parse(JSON.stringify(refund));wrong.event_id='evt_'+String(31).padStart(26,'0');wrong.data.items[0].item_id='txnitm_'+'z'.repeat(26);assert.equal((await process(wrong)).outcome,'review');
 // Partial monetary refunds remain review-only and preserve the other tool.
 const partial=JSON.parse(JSON.stringify(refund));partial.event_id='evt_'+String(34).padStart(26,'0');partial.data.items[0].item_id='txnitm_'+String(2).padStart(26,'0');partial.data.items[0].type='partial';partial.data.items[0].totals.total='100';partial.data.totals.total='100';assert.equal((await process(partial)).outcome,'review');assert.equal((await db.query('SELECT status FROM public.entitlements WHERE product_id=2')).rows[0].status,'active');
 const next=JSON.parse(JSON.stringify(refund));next.event_id='evt_'+String(32).padStart(26,'0');next.data.id='adj_'+'b'.repeat(26);next.data.items[0].item_id='txnitm_'+String(2).padStart(26,'0');next.data.items[0].totals.total='700';next.data.totals.total='700';assert.equal((await process(next)).outcome,'refunded');assert.equal((await db.query('SELECT status FROM public.orders')).rows[0].status,'refunded');assert.equal((await db.query('SELECT status FROM public.entitlements WHERE product_id=3')).rows[0].status,'active');assert.equal((await db.query('SELECT order_number FROM public.orders')).rows[0].order_number,ref);assert.equal((await reserve()).ok,false);
 // Distinct fully-refunded items remain idempotent when replayed out of order.
 const firstAgain=JSON.parse(JSON.stringify(refund));firstAgain.event_id='evt_'+String(33).padStart(26,'0');assert.equal((await process(firstAgain)).outcome,'refunded');assert.equal((await db.query('SELECT status FROM public.orders')).rows[0].status,'refunded');
 const replay=JSON.parse(JSON.stringify(next));replay.notification_id='ntf_'+'b'.repeat(26);assert.equal((await process(replay)).outcome,'refunded');replay.data.totals.total='699';assert.equal((await process(replay)).ok,false);
 // Zero-tax business checkout fulfills at the verified tax-inclusive catalog total.
 const businessBuyer='00000000-0000-4000-8000-000000000003',businessTxn='txn_'+'d'.repeat(26);
 await db.query('INSERT INTO auth.users VALUES($1,now(),null)',[businessBuyer]);
 const businessIntent=(await db.query('SELECT public.reserve_sandbox_cart($1,$2::jsonb) AS r',[businessBuyer,JSON.stringify(items)])).rows[0].r;
 assert.equal(businessIntent.created,true);
 await db.query('SELECT public.finish_sandbox_checkout($1,$2,$3)',[businessBuyer,businessIntent.intent.id,businessTxn]);
 const businessEvent=fixture(40);businessEvent.data.id=businessTxn;businessEvent.data.custom_data.qatools_checkout_id=businessIntent.intent.id;
 businessEvent.data.business_id='biz_'+'c'.repeat(26);businessEvent.data.details.totals.tax='0';businessEvent.data.details.totals.subtotal='1200';
 assert.equal((await process(businessEvent)).outcome,'fulfilled');
 const businessOrder=(await db.query('SELECT subtotal,total FROM public.orders WHERE user_id=$1',[businessBuyer])).rows[0];
 assert.equal(Number(businessOrder.subtotal),12);assert.equal(Number(businessOrder.total),12);
 assert.equal((await db.query("SELECT count(*) AS n FROM public.entitlements WHERE user_id=$1 AND status='active'",[businessBuyer])).rows[0].n,2);
 }finally{await db.close();}
});
