const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),crypto=require('node:crypto');
function load(file,mocks={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,{exports,Buffer,process,Map,Set,URL,Request,Response,Uint8Array,require:n=>n in mocks?mocks[n]:require(n)});return exports;}
const pack=load('src/lib/houdiniPackage.ts',{'server-only':{},'../../public/qatools.json':JSON.parse(fs.readFileSync('public/qatools.json'))}),zip=load('src/lib/adminDownloadUpload.ts',{'server-only':{}}),lib=load('src/lib/preparedTool.ts',{'server-only':{},'./houdiniPackage':pack,'./adminDownloadUpload':zip});
const hda=Buffer.concat([Buffer.from('INDX'),Buffer.alloc(40)]),identity={schema:1,label:'Beautiful Noise',internal_name:'Beautiful_Noise',slug:'beautiful_noise',file:'beautiful_noise.hda',sha256:crypto.createHash('sha256').update(hda).digest('hex')};
function prepared(patch={},entries=[]){return pack.makePackageZip([{name:'qatools-tool.json',bytes:Buffer.from(JSON.stringify({...identity,...patch}))},{name:'beautiful_noise.hda',bytes:hda},...entries]);}
test('prepared tool reads display label, stable underscore slug and matching HDA',()=>{const result=lib.preparedTool(prepared());assert.equal(result.identity.label,'Beautiful Noise');assert.equal(result.identity.slug,'beautiful_noise');assert.equal(result.tool.name,'beautiful_noise.hda');assert.deepEqual(result.tool.bytes,hda);});
test('prepared identity rejects mismatched labels, slugs, hashes, paths and extra content',()=>{for(const patch of [{label:'Other Tool'},{internal_name:'Beautiful_Noise::1.0'},{slug:'beautiful-noise'},{sha256:'a'.repeat(64)},{file:'other.hda'},{schema:2},{extra:true},{label:'../tool'}])assert.throws(()=>lib.preparedTool(prepared(patch)));assert.throws(()=>lib.preparedTool(prepared({},[{name:'extra.py',bytes:Buffer.from('x')}])));const corrupt=prepared();corrupt[50]^=1;assert.throws(()=>lib.preparedTool(corrupt));});
function setup(options={}){
 const calls=[],db={from(table){calls.push({table});const q={select(){return q},eq(){return q},async maybeSingle(){return {data:table==='products'?{id:99,name:identity.label,published:false}:options.existing?{file_path:'old',enabled:true}:null,error:options.readFailure?{}:null}}};return q;},storage:{async getBucket(){return {data:{public:!!options.publicBucket},error:null}},from(){return {async upload(path,bytes){calls.push({upload:path,bytes});return {error:options.uploadFailure?{}:null}},async remove(paths){calls.push({removed:paths});return {error:null}}}}},async rpc(name,args){calls.push({rpc:name,args});return name==='import_prepared_tool'?{data:{id:12,name:identity.label,slug:identity.slug,updated_at:'2026-10-05T12:00:00Z'},error:options.duplicate?{code:'23505'}:null}:{data:{ok:!options.conflict},error:null}}};
 const route=load('src/app/api/admin/products/import/route.ts',{'@/lib/requireAdmin':{requireAdmin:async()=>options.denied?{response:Response.json({error:'Denied'},{status:403})}:{user:{id:'trusted'}}},'@/lib/supabaseAdmin':{supabaseAdmin:db},'@/lib/activationHttp':{privateJson:(v,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store'}})},'@/lib/preparedTool':lib,'@/lib/houdiniPackage':pack});
 return {calls,post:(bytes=prepared())=>route.POST(new Request('http://localhost/api/admin/products/import?requestId=00000000-0000-4000-8000-000000000001',{method:'POST',body:bytes}))};
}
test('import authenticates before parsing or storage and rejects bad ZIPs before creating drafts',async()=>{const denied=setup({denied:true});assert.equal((await denied.post()).status,403);assert.equal(denied.calls.length,0);const invalid=setup();assert.equal((await invalid.post(Buffer.from('bad'))).status,400);assert.equal(invalid.calls.length,0);const publicBucket=setup({publicBucket:true});assert.equal((await publicBucket.post()).status,503);assert.ok(!publicBucket.calls.some(c=>c.rpc));});
test('import creates trusted draft and canonical private installer',async()=>{const s=setup(),response=await s.post();assert.equal(response.status,200);assert.equal(response.headers.get('Cache-Control'),'no-store');assert.equal(s.calls.find(c=>c.rpc).args.p_admin_id,'trusted');const upload=s.calls.find(c=>c.upload);assert.ok(upload.bytes.includes(Buffer.from('qatools/otls/beautiful_noise.hda')));assert.ok(!upload.bytes.includes(Buffer.from('qatools-tool.json')));assert.equal(s.calls.at(-1).rpc,'set_product_download');assert.equal((await response.json()).draft.name,identity.label);});
test('failed installer upload leaves a visible draft and retry uses existing attached package',async()=>{const failed=setup({uploadFailure:true}),response=await failed.post();assert.equal(response.status,503);assert.equal((await response.json()).draft.id,12);const retry=setup({existing:true});assert.equal((await retry.post()).status,200);assert.ok(!retry.calls.some(c=>c.upload));const conflict=setup({conflict:true});assert.equal((await conflict.post()).status,503);assert.ok(conflict.calls.some(c=>c.removed));});
test('duplicate slug returns its real existing product without exposing SQL',async()=>{const s=setup({duplicate:true}),response=await s.post();assert.equal(response.status,409);assert.equal((await response.json()).existingProduct.id,99);assert.ok(!s.calls.some(c=>c.upload));});
