function paymentLibrary(name){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/'+name+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports,process:{env:{PADDLE_ENVIRONMENT:'sandbox'}},require:n=>{if(n==='server-only')return {};throw Error(n);}});return exports;}
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const admin='00000000-0000-0000-0000-000000000001',other='00000000-0000-0000-0000-000000000002';
test('actual SQL unfinished drafts, GIF attachments, publication checks and draft pricing',{skip:!process.env.PGLITE_TEST_MODULE},async()=>{
 const {PGlite}=require(process.env.PGLITE_TEST_MODULE),db=new PGlite();try{
 const remote=fs.readFileSync('supabase/migrations/20261002172027_remote_schema.sql','utf8');const table=n=>remote.slice(remote.indexOf('CREATE TABLE "public"."'+n+'"'),remote.indexOf(';',remote.indexOf('CREATE TABLE "public"."'+n+'"'))+1);
 await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;
 CREATE TABLE auth.users(id uuid PRIMARY KEY,email_confirmed_at timestamptz,banned_until timestamptz);CREATE TABLE admin_users(user_id uuid PRIMARY KEY);
 CREATE TABLE category(id bigint PRIMARY KEY,active boolean);CREATE TABLE complexity(id bigint PRIMARY KEY,active boolean);CREATE TABLE product_downloads(product_id bigint PRIMARY KEY,file_path text,enabled boolean);
 CREATE TABLE sandbox_product_prices(product_id bigint PRIMARY KEY,price_id text,paddle_product_id text,enabled boolean);
 CREATE TABLE sandbox_catalog_setups(product_id bigint PRIMARY KEY,attempt_id uuid DEFAULT gen_random_uuid(),admin_id uuid,slug text,amount_cents integer,status text DEFAULT 'reserved',paddle_product_id text,price_id text,updated_at timestamptz);
 INSERT INTO category VALUES(1,true);INSERT INTO complexity VALUES(1,true);`);
 await db.exec(table('products')+table('product_media'));await db.query('INSERT INTO auth.users VALUES($1,now(),NULL),($2,now(),NULL)',[admin,other]);await db.query('INSERT INTO admin_users VALUES($1)',[admin]);
 const pricing=fs.readFileSync('supabase/migrations/20261004190000_admin_paddle_catalog_setup.sql','utf8');await db.exec(pricing.slice(pricing.indexOf('CREATE FUNCTION public.advance_sandbox_catalog_setup'),pricing.indexOf('CREATE FUNCTION public.complete_sandbox_catalog_setup')));
 for(const file of ['20261005100000_product_drafts.sql','20261005110000_product_main_image.sql','20261005120000_product_publication_workflow.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+file,'utf8'));
 await db.exec("ALTER TABLE product_downloads ADD FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE; CREATE TABLE test_commercial_records(product_id bigint REFERENCES products(id));");
 await db.exec("INSERT INTO products(id,name,slug,price_eur,current_version,published) VALUES(20,'manual','manual',NULL,'',false)");
 await db.exec(fs.readFileSync('supabase/migrations/20261005130000_product_draft_identity.sql','utf8'));
 assert.equal((await db.query("SELECT nextval(pg_get_serial_sequence('public.products','id')) id")).rows[0].id,21);
 const temporary=(await db.query("INSERT INTO products(name,slug,current_version,published) VALUES('qatesta01','qatesta01','',false) RETURNING id,updated_at")).rows[0];
 const discard=(who=admin,stamp=temporary.updated_at)=>db.query('SELECT delete_unused_product_draft($1,$2,$3)',[who,temporary.id,stamp]);
 await assert.rejects(discard(other),/Admin access/);await assert.rejects(discard(admin,'2000-01-01'),/Draft changed/);
 await db.query('INSERT INTO test_commercial_records VALUES($1)',[temporary.id]);await assert.rejects(discard(),/linked records/);await db.exec('DELETE FROM test_commercial_records');
 await db.query("INSERT INTO product_members VALUES(20,$1)",[temporary.id]);await assert.rejects(discard(),/linked records/);await db.exec('DELETE FROM product_members');
 await db.query("UPDATE products SET initial_release_date=current_date WHERE id=$1",[temporary.id]);await assert.rejects(discard(),/Previously released/);await db.query('UPDATE products SET initial_release_date=NULL WHERE id=$1',[temporary.id]);
 await db.query("INSERT INTO product_downloads VALUES($1,'unused.zip',true)",[temporary.id]);await discard();
 assert.equal((await db.query('SELECT count(*)::int n FROM product_downloads WHERE product_id=$1',[temporary.id])).rows[0].n,0);
 await db.exec("INSERT INTO products(name,slug,current_version,published) VALUES('qatesta01','qatesta01','',false)");
 for(const role of ['anon','authenticated','service_role'])assert.equal((await db.query("SELECT has_function_privilege($1,'delete_unused_product_draft(uuid,bigint,timestamptz)','EXECUTE') a",[role])).rows[0].a,role==='service_role');
 const draft={name:'qatest01',product_type:'tool',subtitle:'',description:'',price_eur:null,compatibility:'',current_version:'',release_date:null,category_id:0,complexity_id:0,tool_ids:[]};
 async function save(data=draft,id=null,stamp=null){return (await db.query('SELECT save_product_draft($1,$2,$3,$4,$5) r',[admin,other,data,id,stamp])).rows[0].r;}
 let saved=await save();assert.deepEqual(await save(),saved);const row=(await db.query('SELECT * FROM products WHERE id=$1',[saved.id])).rows[0];assert.equal(row.category_id,null);assert.equal(row.price_eur,null);
 async function checks(who=admin){return (await db.query('SELECT product_publication_checks($1,$2) r',[who,saved.id])).rows[0].r;}
 let c=await checks();assert.equal(c.ready,false);assert.ok(c.missing.includes('Valid price'));assert.ok(!c.missing.includes('Included tools'));await assert.rejects(checks(other),/Admin access/);
 await assert.rejects(db.query('SELECT publish_product_draft($1,$2,$3)',[admin,saved.id,saved.updated_at]),/Publication requirements/);
 saved=await save({...draft,subtitle:'Tool',description:'Description',compatibility:'Houdini 22',current_version:'1',price_eur:0,category_id:1,complexity_id:1},saved.id,saved.updated_at);
 saved=(await db.query('SELECT set_product_draft_card($1,$2,NULL,$3,$4) r',[admin,saved.id,saved.updated_at,'drafts/'+saved.id+'/00000000-0000-0000-0000-000000000010.gif'])).rows[0].r;
 await db.query("INSERT INTO product_downloads VALUES($1,'release.zip',true)",[saved.id]);assert.equal((await checks()).ready,true);
 const stale=saved.updated_at;
 saved=await save({...draft,subtitle:'Tool',description:'Description',compatibility:'Houdini 22',current_version:'1',price_eur:5,category_id:1,complexity_id:1},saved.id,saved.updated_at);
 assert.ok((await checks()).missing.includes('Verified Paddle price'));
 const pro='pro_'+'a'.repeat(26),pri='pri_'+'b'.repeat(26);
 const reserved=(await db.query('SELECT reserve_sandbox_catalog_setup($1,$2,$3,500) r',[admin,saved.id,draft.name])).rows[0].r;assert.equal(reserved.ok,true);assert.equal(reserved.created,true);assert.equal((await db.query('SELECT reserve_sandbox_catalog_setup($1,$2,$3,500) r',[admin,saved.id,draft.name])).rows[0].r.created,false);
 const attempt=reserved.job.attempt_id;
 assert.equal((await db.query("SELECT advance_sandbox_catalog_setup($1,$2,'reserved','product_ready',$3,NULL) r",[admin,attempt,pro])).rows[0].r,true);
 assert.equal((await db.query("SELECT advance_sandbox_catalog_setup($1,$2,'product_ready','price_ready',$3,$4) r",[admin,attempt,pro,pri])).rows[0].r,true);
 await db.query('UPDATE products SET price_eur=6 WHERE id=$1',[saved.id]);assert.equal((await db.query('SELECT complete_sandbox_catalog_setup($1,$2) r',[admin,attempt])).rows[0].r,false);
 await db.query('UPDATE products SET price_eur=5 WHERE id=$1',[saved.id]);assert.equal((await db.query('SELECT complete_sandbox_catalog_setup($1,$2) r',[admin,attempt])).rows[0].r,true);
 assert.equal((await checks()).ready,true);await assert.rejects(db.query('SELECT publish_product_draft($1,$2,$3,$4)',[admin,saved.id,stale,pri]),/Draft changed/);await assert.rejects(db.query('SELECT publish_product_draft($1,$2,$3,$4)',[admin,saved.id,saved.updated_at,'pri_'+'c'.repeat(26)]),/Price changed/);
 await db.query('SELECT publish_product_draft($1,$2,$3,$4)',[admin,saved.id,saved.updated_at,pri]);const published=(await db.query('SELECT published,release_date FROM products WHERE id=$1',[saved.id])).rows[0];assert.equal(published.published,true);assert.ok(published.release_date);
 await db.query("UPDATE products SET published=false,release_date='2000-01-01' WHERE id=$1",[saved.id]);const stamp=(await db.query('SELECT updated_at FROM products WHERE id=$1',[saved.id])).rows[0].updated_at;await db.query('SELECT publish_product_draft($1,$2,$3,$4)',[admin,saved.id,stamp,pri]);assert.deepEqual((await db.query('SELECT release_date FROM products WHERE id=$1',[saved.id])).rows[0].release_date,published.release_date);
 await db.query("SELECT save_product_draft($1,$2,$3)",[admin,'00000000-0000-0000-0000-000000000003',{...draft,name:'qabundle01',product_type:'bundle',tool_ids:[saved.id]}]);
 await db.exec('GRANT SELECT ON products TO anon; SET ROLE anon');assert.equal((await db.query('SELECT * FROM product_members')).rows.length,0);await assert.rejects(db.exec('INSERT INTO product_members VALUES(2,1)'),/permission denied/);await db.exec('RESET ROLE');
 for(const role of ['anon','authenticated','service_role'])assert.equal((await db.query("SELECT has_function_privilege($1,'publish_product_draft(uuid,bigint,timestamptz,text)','EXECUTE') a",[role])).rows[0].a,role==='service_role');
 await assert.rejects(db.exec("INSERT INTO products(name,slug,price_eur,current_version,category_id,complexity_id,published) VALUES('bad','bad',NULL,'',NULL,NULL,true)"),/published_metadata_present/);
 }finally{await db.close();}
});
test('readiness route independently authorizes and rejects malformed references',async()=>{
 for(const denied of [false,true]){const calls=[],exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/app/api/admin/products/readiness/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports,URL,Number,require(n){if(n==='@/lib/paddleEnvironment')return paymentLibrary('paddleEnvironment');if(n==='@/lib/paddleScope')return paymentLibrary('paddleScope');if(n==='@/lib/requireAdmin')return {requireAdmin:async()=>denied?{response:Response.json({error:'Denied'},{status:403})}:{user:{id:admin}}};if(n==='@/lib/paddleCartDatabase')return {paddleCartDatabase:{rpc:async(name,args)=>{calls.push(args);return {data:{ready:false,missing:["Main image"]},error:null};}}};if(n==='@/lib/paddleCartCatalog')return {verifyCatalogPrice:async()=>{}};if(n==='@/lib/activationHttp')return {privateJson:(v,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store'}})};if(n==='@/lib/supabaseAdmin')return {supabaseAdmin:{rpc:async(name,args)=>{calls.push(args);return {data:{ready:false,missing:['Main image']},error:null};}}};throw Error(n);}});
 const r=await exports.GET(new Request('http://localhost/api/admin/products/readiness?productId=1&adminId=forged'));assert.equal(r.status,denied?403:200);assert.equal(r.headers.get('cache-control'),'no-store');if(denied)assert.equal(calls.length,0);else{assert.equal(calls[0].p_admin_id,admin);assert.equal((await exports.GET(new Request('http://localhost/api/admin/products/readiness?productId=bad'))).status,400);}
 }
});

test('readiness cannot call a mismatched provider price ready',async()=>{for(const fail of [false,true]){const exports={},queries=[];const db={from(table){const q={select(){return q;},eq(){return q;},maybeSingle:async()=>({data:table==='products'?{id:1,slug:'qatest01',price_eur:5,published:false}:{product_id:1,price_id:'pri_saved',paddle_product_id:'pro_saved',enabled:true},error:null})};return q;},rpc:async()=>({data:{ready:true,missing:[],updated_at:'2026-10-05'},error:null})};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/app/api/admin/products/readiness/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports,URL,Number,Error,require(n){if(n==='@/lib/paddleEnvironment')return paymentLibrary('paddleEnvironment');if(n==='@/lib/paddleScope')return paymentLibrary('paddleScope');if(n==='@/lib/requireAdmin')return {requireAdmin:async()=>({user:{id:admin}})};if(n==='@/lib/supabaseAdmin')return {supabaseAdmin:db};if(n==='@/lib/paddleCartDatabase')return {paddleCartDatabase:db};if(n==='@/lib/paddleCartCatalog')return {verifyCatalogPrice:async(p,m)=>{queries.push({p,m});if(fail)throw Error('secret diagnostic');}};if(n==='@/lib/activationHttp')return {privateJson:Response.json};throw Error(n);}});const r=await exports.GET(new Request('http://localhost/api/admin/products/readiness?productId=1'));const body=await r.json();assert.equal(body.ready,!fail);assert.equal(queries.length,1);assert.ok(!JSON.stringify(body).includes('secret'));if(fail)assert.ok(body.missing.length);}});
