const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const stamp='2026-10-08T10:00:00Z',content={subtitle:'New subtitle',description:'New description',category_id:2,complexity_id:2};
function load(file,mocks){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,Request,Response,Buffer,Date,Number,require:n=>n in mocks?mocks[n]:require(n)});return exports;}
function setup(error,denied=false){const calls=[];return {calls,route:load('src/app/api/admin/products/content/route.ts',{'@/lib/requireAdmin':{requireAdmin:async()=>denied?{response:Response.json({error:'Denied'},{status:403})}:{user:{id:'trusted'}}},'@/lib/supabaseAdmin':{supabaseAdmin:{rpc:async(name,args)=>{calls.push({name,args});return {error,data:error?null:{id:1,updated_at:stamp,media:[]}};}}},'@/lib/productContent':load('src/lib/productContent.ts',{}),'@/lib/activationHttp':{privateJson:(b,status=200)=>Response.json(b,{status,headers:{'Cache-Control':'no-store'}}),readActivationBody:async(r,max)=>{const b=await r.text();return b.length>max?null:JSON.parse(b);}}})};}
const body={productId:1,expectedUpdatedAt:stamp,content,media:null};
const request=b=>new Request('http://localhost/api/admin/products/content',{method:'PUT',body:JSON.stringify(b)});
test('published content requires admin and accepts only the approved fields',async()=>{
 const denied=setup(null,true);assert.equal((await denied.route.PUT(request(body))).status,403);assert.equal(denied.calls.length,0);
 for(const b of [{...body,admin:'spoof'},{...body,productId:0},{...body,expectedUpdatedAt:'bad'},{...body,media:[{id:1,role:'unknown',path:'a'}]},...['price_eur','slug','tool_ids'].map(k=>({...body,content:{...content,[k]:5}})),...['subtitle','description'].map(k=>({...body,content:{...content,[k]:' '}})),{...body,content:{...content,category_id:1.5}}]){const s=setup();assert.equal((await s.route.PUT(request(b))).status,400);assert.equal(s.calls.length,0);}
 const s=setup();assert.equal((await s.route.PUT(request(body))).status,200);assert.equal(s.calls[0].name,'save_published_product_content');assert.equal(s.calls[0].args.p_admin_id,'trusted');assert.equal(s.calls[0].args.p_media,null);
 for(const [code,status] of [['40001',409],['22023',400],['42501',403],['unexpected',503]]){const s=setup({code,message:'private database secret'}),r=await s.route.PUT(request(body));assert.equal(r.status,status);assert.equal(r.headers.get('Cache-Control'),'no-store');assert.ok(!(await r.text()).includes('private database secret'));}
});
test('actual PostgreSQL content and artwork update atomically without changing commerce',{skip:!process.env.PGLITE_TEST_MODULE},async()=>{
 const {PGlite}=require(process.env.PGLITE_TEST_MODULE),db=new PGlite();try{
 const remote=fs.readFileSync('supabase/migrations/20261002172027_remote_schema.sql','utf8'),table=n=>{const at=remote.indexOf('CREATE TABLE "public"."'+n+'"');return remote.slice(at,remote.indexOf(';',at)+1);};
 await db.exec("CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE SCHEMA storage;CREATE TABLE auth.users(id uuid PRIMARY KEY,email_confirmed_at timestamptz,banned_until timestamptz);CREATE TABLE admin_users(user_id uuid PRIMARY KEY);CREATE TABLE storage.buckets(id text,public boolean);CREATE TABLE storage.objects(bucket_id text,name text);INSERT INTO storage.buckets VALUES('product-media',true)");await db.exec(table('products')+table('product_media')+table('category')+table('complexity'));
 for(const f of ['20261008100000_explicit_product_artwork_update.sql','20261008120000_published_product_content.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+f,'utf8'));
 const admin='00000000-0000-4000-8000-000000000001',buyer='00000000-0000-4000-8000-000000000002';await db.query('INSERT INTO auth.users VALUES($1,now(),null),($2,now(),null)',[admin,buyer]);await db.query('INSERT INTO admin_users VALUES($1)',[admin]);
 await db.exec("INSERT INTO category(id,name,slug,active) VALUES(1,'old','old',false),(2,'new','new',true),(3,'inactive','inactive',false);INSERT INTO complexity(id,name,slug,active) VALUES(1,'old','old',false),(2,'new','new',true),(3,'inactive','inactive',false);INSERT INTO products(id,name,slug,subtitle,description,price_eur,current_version,published,category_id,complexity_id) VALUES(1,'one','one','Old','Old description',5,'1',true,1,1),(2,'draft','draft','Old','Old description',5,'1',false,1,1);INSERT INTO product_media(product_id,media_type,file_path,role,sort_order) VALUES(1,'image','card.png','card',0),(1,'image','gallery.png','gallery',1)");
 let version=(await db.query('SELECT updated_at::text t FROM products WHERE id=1')).rows[0].t;
 const original=(await db.query('SELECT * FROM products WHERE id=1')).rows[0],media=(await db.query('SELECT id,role,file_path AS path FROM product_media ORDER BY id')).rows;
 const apply=(c=content,m=null,who=admin,v=version,id=1)=>db.query('SELECT save_published_product_content($1,$2,$3,$4,$5) r',[who,id,v,JSON.stringify(c),m===null?null:JSON.stringify(m)]);
 await assert.rejects(apply(content,null,buyer),/Admin access/);await assert.rejects(apply(content,null,admin,version,2),/Product changed/);
 for(const c of [{...content,price_eur:1},{...content,category_id:3},{...content,complexity_id:999},{...content,category_id:1.5},{...content,subtitle:''}])await assert.rejects(apply(c),/Invalid/);
 // A media rejection leaves both text and images unchanged, including the version.
 await assert.rejects(apply(content,[{...media[0],path:'wrong'},media[1]]));assert.deepEqual((await db.query('SELECT * FROM products WHERE id=1')).rows[0],original);assert.deepEqual((await db.query('SELECT id,role,file_path AS path FROM product_media ORDER BY id')).rows,media);
 // Keeping an existing inactive tag is allowed; choosing a different inactive tag is refused.
 let result=(await apply({...content,category_id:1,complexity_id:1})).rows[0].r;const stale=version;version=result.updated_at;await assert.rejects(apply(content,null,admin,stale),/Product changed/);
 assert.deepEqual((await db.query('SELECT id,role,file_path AS path FROM product_media ORDER BY id')).rows,media);
 const path='drafts/1/00000000-0000-4000-8000-000000000005.png';await db.query("INSERT INTO storage.objects VALUES('product-media',$1)",[path]);result=(await apply(content,[{...media[0],path},media[1]])).rows[0].r;assert.equal(result.media[0].file_path,path);
 const after=(await db.query('SELECT * FROM products WHERE id=1')).rows[0];for(const key of ['subtitle','description','category_id','complexity_id','updated_at'])delete after[key];const protectedFields={...original};for(const key of ['subtitle','description','category_id','complexity_id','updated_at'])delete protectedFields[key];assert.deepEqual(after,protectedFields);
 for(const role of ['anon','authenticated'])assert.equal((await db.query("SELECT has_function_privilege($1,'save_published_product_content(uuid,bigint,timestamptz,jsonb,jsonb)','EXECUTE') allowed",[role])).rows[0].allowed,false);
 }finally{await db.close();}
});

test('client commits published text and staged images through one explicit update',async()=>{
 const calls=[],exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/components/AdminGallery.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,{exports,URL,URLSearchParams,fetch:async(url,options)=>{calls.push({url,options});return Response.json(options.method==='POST'?{path:'drafts/1/new.png'}:{gallery:{id:1,updated_at:stamp,media:[]}});},require:n=>n==='next/image'?{__esModule:true,default:()=>null}:n==='@/lib/supabase'?{supabase:{auth:{getSession:async()=>({data:{session:{access_token:'token'}},error:null})}}}:require(n)});
 await exports.saveArtwork(1,stamp,null,content);assert.equal(calls.length,1);assert.equal(calls[0].url,'/api/admin/products/content');assert.deepEqual(JSON.parse(calls[0].options.body),body);
 calls.length=0;await exports.saveArtwork(1,stamp,[{id:1,role:'card',sort_order:0,file_path:'old.png',file:new Blob(['image'])}],content);assert.equal(calls.length,2);assert.equal(calls[0].options.method,'POST');assert.equal(calls[1].url,'/api/admin/products/content');const payload=JSON.parse(calls[1].options.body);assert.deepEqual(payload.content,content);assert.equal(payload.media[0].path,'drafts/1/new.png');assert.equal(payload.expectedUpdatedAt,stamp);
});
