import type { Metadata } from "next";
import InformationPage from "@/components/InformationPage";
import {operator,supportHref} from "@/lib/siteOperator";
export const metadata:Metadata={title:"Refunds | qatools",robots:{index:false,follow:true}};
export default function RefundsPage(){return <InformationPage title="Refunds" policy>
<section><h2>Requesting a refund</h2><p>Contact <a href={supportHref}>{operator.email}</a> within 14 days of purchase with your order reference and reason for requesting a refund. We review requests individually. Submitting a request does not guarantee approval.</p><p>Include your account email and the product name. Do not send your password, activation key or payment-card details. You can also request payment help through <a href="https://paddle.net">Paddle buyer support</a>.</p></section>
<section><h2>Your consumer rights</h2><p>The 14-day request window describes our discretionary policy; it does not limit your statutory consumer rights. Faulty or incorrectly described products and applicable withdrawal rights are handled separately.</p><p>Digital-content withdrawal exceptions depend on applicable law and the express consent given when delivery begins. Downloading alone does not automatically remove all consumer rights.</p><p>Paddle&apos;s <a href="https://www.paddle.com/legal/refund-policy">refund policy</a> also applies to its reseller role. Where mandatory rights or a more protective applicable policy apply, those rights remain available.</p></section>
<section><h2>After approval</h2><p>Payment refunds are processed through Paddle. Payment-provider and bank processing times may vary.</p><p>A full refund removes access supplied by the refunded purchase. Downloads and future license renewals for that access are blocked. Existing signed offline authorization may remain usable until a successful check or its expiry.</p><p>Independent ownership is preserved: refunding a bundle does not remove a tool bought separately. Previous orders and original invoices remain in your history, and a fully refunded product can be purchased again.</p></section>
</InformationPage>;}
