window.QA_PRODUCTS = [
  {
    "id": "qafit01",
    "title": "qafit01",
    "subtitle": "fits values to 0\u20131",
    "category": "SOP",
    "complexity": "SIMPLE",
    "price": 5,
    "popularity": 95,
    "relevance": 100,
    "date": "2026-09-30",
    "image": "product_01.png",
    "description": "Remaps any incoming attribute value to a 0\u20131 range. It takes the minimum and maximum available values of the attribute and fits the range between 0 and 1. Simple but effective.",
    "version": "v1.0",
    "compatibility": "H21",
    "update_date": "2026-09-30"
  },
  {
    "id": "qasim02",
    "title": "qasim02",
    "subtitle": "quick simulation setup",
    "category": "DOP",
    "complexity": "MEDIUM",
    "price": 10,
    "popularity": 62,
    "relevance": 75,
    "date": "2026-05-18",
    "image": "product_02.png",
    "description": "A compact setup helper for simulation workflows.",
    "version": "v1.0",
    "compatibility": "H21",
    "update_date": "2026-08-03"
  },
  {
    "id": "qacomplex03",
    "title": "qacomplex03",
    "subtitle": "advanced attribute workflow",
    "category": "SOP",
    "complexity": "COMPLEX",
    "price": 30,
    "popularity": 80,
    "relevance": 58,
    "date": "2025-12-02",
    "image": "product_03.png",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "version": "v1.0",
    "compatibility": "H21",
    "update_date": "2026-04-14"
  },
  {
    "id": "qarender04",
    "title": "qarender04",
    "subtitle": "compact render output helper",
    "category": "ROP",
    "complexity": "SIMPLE",
    "price": 20,
    "popularity": 73,
    "relevance": 66,
    "date": "2026-02-11",
    "image": "product_04.png",
    "description": "A small utility for streamlining output and render preparation.",
    "version": "v1.0",
    "compatibility": "H21",
    "update_date": "2026-06-22"
  },
  {
    "id": "qashelf05",
    "title": "qashelf05",
    "subtitle": "one-click shelf utility",
    "category": "SHELF TOOL",
    "complexity": "SIMPLE",
    "price": 5,
    "popularity": 48,
    "relevance": 52,
    "date": "2025-08-27",
    "image": "product_05.png",
    "description": "A lightweight shelf utility designed for one-click access.",
    "version": "v1.0",
    "compatibility": "H21",
    "update_date": "2026-01-19"
  },
  {
    "id": "qadynamics06",
    "title": "qadynamics06",
    "subtitle": "faster dynamics preparation",
    "category": "DOP",
    "complexity": "COMPLEX",
    "price": 30,
    "popularity": 88,
    "relevance": 82,
    "date": "2026-07-07",
    "image": "product_06.png",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vel sem at sapien bibendum tempor. Praesent vitae nibh ut velit facilisis luctus. Curabitur sit amet mi non justo gravida posuere. Duis commodo, orci sed cursus posuere, massa mi placerat lacus, sed faucibus purus justo non augue.",
    "version": "v1.0",
    "compatibility": "H21",
    "update_date": "2026-09-02"
  }
];
window.QA_PURCHASED_IDS = ["qafit01", "qasim02", "qarender04"];
