import type { Metadata } from "next";
import Link from "next/link";
import InformationPage from "@/components/InformationPage";
import {operator,supportHref} from "@/lib/siteOperator";
export const metadata:Metadata={title:"Terms and license | qatools",robots:{index:false,follow:true}};
export default function TermsPage(){return <InformationPage title="Terms and license" policy>
<section><h2>About qatools</h2><p>The website operator is identified in our <Link href="/legal">Legal notice</Link>. Contact <a href={supportHref}>{operator.email}</a>. The website provides digital tools, bundles and project files for SideFX Houdini.</p><p>Check each product&apos;s contents and compatibility before purchasing. Current installation instructions cover Houdini 22 on Windows; other versions and platforms should not be assumed compatible.</p></section>
<section><h2>Your account and purchases</h2><p>An account is required to acquire products and access downloads. Paid products are one-time purchases, not recurring subscriptions. Payment confirmation from the provider is required before access is granted.</p><p>Our order process uses Paddle as the reseller. Its <a href="https://www.paddle.com/legal/buyer-terms">buyer terms</a> apply to its payment and order services. Your mandatory consumer rights remain unaffected.</p></section>
<section><h2>Account licensing</h2><p>One account activation key covers the products you own, with one active computer assigned to the account. Keep your password and activation key private. The key does not unlock products you have not acquired.</p><p>Changing Houdini version does not itself require a new account key. Tool compatibility is separate. Contact <Link href="/support">support</Link> to release an old computer before activating its replacement.</p></section>
<section><h2>Offline use</h2><p>Activation and periodic license renewal require internet access. Updated installers allow offline work with a valid signed local license for up to seven days after successful renewal. Reconnect and refresh the license before that authorization expires.</p><p>A failed connection preserves a still-valid cached license. Normal tool cooking verifies the license locally. After a machine release, the old computer cannot renew; its offline authorization may remain valid until a successful check or its expiry.</p></section>
<section><h2>Bundles and projects</h2><p>A bundle or project has its own fixed price and includes the tools identified for that purchase. Already-owned tools do not reduce the price. Your access from an independent purchase is preserved separately.</p></section>
<section><h2>Refunds and access</h2><p>See our <Link href="/refunds">refund policy</Link> for requests. An approved full refund removes downloads and future license access supplied by that purchase. A cached offline license may remain valid until a successful check or expiry.</p><p>Refunding a bundle or project does not remove a tool you still own through a separate active purchase or another valid acquisition. Order and original invoice history are retained. A fully refunded product may be purchased again.</p></section>
<section><h2>Contact</h2><p>For installation, licensing or product questions, visit <Link href="/support">Support</Link>. Nothing on this page excludes rights that cannot lawfully be excluded.</p></section>
</InformationPage>;}
