import type { Metadata } from "next";
import InformationPage from "@/components/InformationPage";
import {operator,supportHref} from "@/lib/siteOperator";
export const metadata:Metadata={title:"Privacy | qatools",robots:{index:false,follow:true}};
export default function PrivacyPage(){return <InformationPage title="Privacy" policy>
<section><h2>Who is responsible</h2><p>{operator.name}, based in {operator.country}, operates qatools and is responsible for its account, product delivery and licensing data. Contact <a href={supportHref}>{operator.email}</a> for privacy questions or requests.</p></section>
<section><h2>Information used by qatools</h2><ul><li>Account email, profile name, optional profile/billing information and authentication/session records.</li><li>Purchased products, orders, provider references, prices, currencies, refunds and access records.</li><li>Machine identifiers and names, activation history and account-linked licensing records.</li><li>Authorized download requests, including free and paid request counts.</li><li>Connection/security information and support messages you send us.</li></ul><p>License requests use a machine identifier and product ownership to authorize the correct computer. A machine name is a readable label, not the sole identifier. The website does not handle raw payment-card details; those are entered into Paddle&apos;s checkout.</p></section>
<section><h2>Why information is used</h2><p>Account, order and licensing information provides the service you request: authentication, downloads, invoices and authorized tool use. Security information helps protect accounts, prevent abuse and investigate failures. Support messages let us answer your requests.</p><p>The intended legal bases are performance of the requested service, legitimate interests in service security and support, and legal obligations where applicable. Before live sales, the final notice will specify these bases and retention arrangements for each relevant purpose.</p></section>
<section><h2>Services involved</h2><p>Supabase provides authentication, database and file storage. Vercel hosts the website and server endpoints. Resend delivers account emails through our configured SMTP service. Paddle handles checkout, payments and invoice operations as a reseller and publishes its own <a href="https://www.paddle.com/legal/privacy">privacy notice</a>.</p><p>The final notice will identify the applicable provider roles and international-transfer safeguards based on the actual service settings and agreements.</p></section>
<section><h2>Browser and local storage</h2><p>The website uses browser storage for login sessions, likes and cart contents. Admin draft recovery stores pending edits and files in the administrator&apos;s browser. Houdini keeps a signed local licensing cache on your computer for offline verification.</p><p>No advertising analytics integration has been identified in our application code. Third-party checkout and hosting services may process their own connection or security information; this draft does not claim that they use no cookies or tracking.</p></section>
<section><h2>Retention</h2><p>The final schedule will distinguish active account and licensing records, purchase records required for legal or dispute purposes, short-lived security information, and support correspondence. Account closure does not automatically erase records that must lawfully be retained.</p><p>Specific retention periods and provider settings are still being confirmed before live sales. This draft does not promise a deletion schedule that has not been implemented.</p></section>
<section><h2>Your rights and requests</h2><p>Subject to applicable conditions, you can request access, correction, erasure, restriction or portability of your personal data, and object to processing where the law permits. Where processing relies on consent, you may withdraw that consent.</p><p>Send requests to <a href={supportHref}>{operator.email}</a>. We may need to verify your identity safely before acting. Never send a password or activation key. Some records may need to be retained to meet legal obligations or establish legal claims.</p><p>You may lodge a complaint with a competent data protection authority, including Spain&apos;s <a href="https://www.aepd.es">Agencia Española de Protección de Datos</a>.</p></section>
</InformationPage>;}
