-- Account machine foundation. Signed-license issuance/renewal is a later step.
BEGIN;
SET LOCAL lock_timeout = '5s';
LOCK TABLE public.license_activations IN SHARE ROW EXCLUSIVE MODE;

-- Never silently select a computer when legacy tools disagree.
DO $$
BEGIN
  IF EXISTS (
    SELECT user_id FROM public.license_activations WHERE status = 'active'
    GROUP BY user_id HAVING count(DISTINCT machine_id) > 1
  ) THEN
    RAISE EXCEPTION 'Account migration stopped: an account has multiple active machine IDs. Review legacy activations before retrying.';
  END IF;
END $$;

CREATE TABLE public.account_activations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  machine_id text NOT NULL CHECK (length(btrim(machine_id)) > 0),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'released', 'revoked')),
  activated_at timestamptz NOT NULL DEFAULT now(),
  released_at timestamptz,
  released_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (status <> 'active' OR (released_at IS NULL AND released_by IS NULL)),
  CHECK (status <> 'released' OR released_at IS NOT NULL)
);
CREATE UNIQUE INDEX account_activations_one_active_machine_per_user
  ON public.account_activations(user_id) WHERE status = 'active';
CREATE INDEX account_activations_user_history ON public.account_activations(user_id, activated_at DESC);
CREATE TRIGGER account_activations_set_updated_at BEFORE UPDATE ON public.account_activations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Only carry forward active assignments; preserve every original record unchanged.
INSERT INTO public.account_activations(user_id, machine_id, activated_at)
SELECT user_id, machine_id, min(activated_at)
FROM public.license_activations WHERE status = 'active'
GROUP BY user_id, machine_id;

ALTER TABLE public.account_activations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can read own account activations" ON public.account_activations
  FOR SELECT TO authenticated USING ((SELECT auth.uid()) = user_id);
-- Explicitly override inherited defaults, including supabase_admin defaults.
REVOKE ALL ON public.account_activations FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE public.account_activations_id_seq FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON public.account_activations TO authenticated, service_role;
GRANT UPDATE(status, released_at, released_by) ON public.account_activations TO service_role;

-- Legacy table becomes read-only for app roles; SQL owner retains historical access.
REVOKE ALL ON public.license_activations FROM PUBLIC, anon, authenticated, service_role;
REVOKE UPDATE(status, released_at, released_by) ON public.license_activations FROM service_role;
GRANT SELECT ON public.license_activations TO authenticated, service_role;
COMMENT ON TABLE public.license_activations IS
  'Legacy per-tool history frozen at account-machine cutover. Status is historical, not current account authorization.';
COMMENT ON TABLE public.account_activations IS
  'Current account machine assignment/history. Product access separately requires active entitlements; signed licensing integration pending.';

DO $$
DECLARE browser_role text;
BEGIN
  FOREACH browser_role IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF has_any_column_privilege(browser_role, 'public.account_activations', 'INSERT,UPDATE')
      OR has_table_privilege(browser_role, 'public.account_activations', 'DELETE,TRUNCATE,REFERENCES,TRIGGER,MAINTAIN') THEN
      RAISE EXCEPTION 'Browser role has unsafe account activation privileges';
    END IF;
  END LOOP;
  IF has_any_column_privilege('service_role', 'public.license_activations', 'INSERT,UPDATE') THEN
    RAISE EXCEPTION 'Legacy activation writes must be disabled';
  END IF;
END $$;
COMMIT;
