SET local check_function_bodies = off;

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "service_role";

CREATE TABLE "public"."admin_users" (
  "user_id"    uuid                     NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "admin_users_pkey" PRIMARY KEY (user_id)
);

ALTER TABLE "public"."admin_users"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."category" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."categories_id_seq") NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "name"       text                     NOT NULL DEFAULT ''::text,
  "slug"       text                     NOT NULL DEFAULT ''::text,
  "sort_order" smallint                 NOT NULL DEFAULT '0'::smallint,
  "active"     boolean                  NOT NULL DEFAULT true,
  CONSTRAINT "categories_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."category"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."complexity" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."complexities_id_seq") NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "name"       text                     NOT NULL DEFAULT ''::text,
  "slug"       text                     NOT NULL DEFAULT ''::text,
  "sort_order" smallint                 NOT NULL DEFAULT '0'::smallint,
  "active"     boolean                  NOT NULL DEFAULT true,
  CONSTRAINT "complexities_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."complexity"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."entitlements" (
  "id"            bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"       uuid                     NOT NULL,
  "product_id"    bigint                   NOT NULL,
  "order_item_id" bigint,
  "source"        text                     NOT NULL DEFAULT 'purchase'::text,
  "status"        text                     NOT NULL DEFAULT 'active'::text,
  "granted_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "revoked_at"    timestamp with time zone,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"    timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "entitlements_pkey" PRIMARY KEY (id),
  CONSTRAINT "entitlements_source_check" CHECK ((source = ANY (ARRAY['purchase'::text, 'free'::text, 'admin'::text]))),
  CONSTRAINT "entitlements_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'refunded'::text, 'revoked'::text]))),
  CONSTRAINT "entitlements_user_product_unique" UNIQUE (user_id, product_id)
);

ALTER TABLE "public"."entitlements"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."license_activations" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entitlement_id" bigint                   NOT NULL,
  "user_id"        uuid                     NOT NULL,
  "product_id"     bigint                   NOT NULL,
  "machine_id"     text                     NOT NULL,
  "status"         text                     NOT NULL DEFAULT 'active'::text,
  "activated_at"   timestamp with time zone NOT NULL DEFAULT now(),
  "released_at"    timestamp with time zone,
  "created_at"     timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"     timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "license_activations_pkey" PRIMARY KEY (id),
  CONSTRAINT "license_activations_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'released'::text, 'revoked'::text])))
);

ALTER TABLE "public"."license_activations"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."order_items" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id"   bigint                   NOT NULL,
  "product_id" bigint                   NOT NULL,
  "quantity"   integer                  NOT NULL DEFAULT 1,
  "unit_price" numeric(12,2)            NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "order_items_pkey" PRIMARY KEY (id),
  CONSTRAINT "order_items_quantity_check" CHECK ((quantity > 0))
);

ALTER TABLE "public"."order_items"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."orders" (
  "id"                      bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"                 uuid                     NOT NULL,
  "provider"                text                     NOT NULL DEFAULT 'paddle'::text,
  "provider_order_id"       text,
  "provider_transaction_id" text,
  "status"                  text                     NOT NULL DEFAULT 'pending'::text,
  "currency"                text                     NOT NULL DEFAULT 'EUR'::text,
  "subtotal"                numeric(12,2)            NOT NULL DEFAULT 0,
  "total"                   numeric(12,2)            NOT NULL DEFAULT 0,
  "provider_created_at"     timestamp with time zone,
  "created_at"              timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"              timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "orders_pkey" PRIMARY KEY (id),
  CONSTRAINT "orders_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'paid'::text, 'refunded'::text, 'partially_refunded'::text, 'cancelled'::text])))
);

ALTER TABLE "public"."orders"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."product_media" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  "product_id"   bigint                   NOT NULL,
  "media_type"   text                     NOT NULL,
  "file_path"    text,
  "external_url" text,
  "role"         text                     NOT NULL,
  "sort_order"   smallint                 NOT NULL,
  CONSTRAINT "product_media_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."product_media"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."products" (
  "id"                    bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"            timestamp with time zone NOT NULL DEFAULT now(),
  "name"                  text                     NOT NULL DEFAULT ''::text,
  "slug"                  text                     NOT NULL DEFAULT ''::text,
  "subtitle"              text                     NOT NULL DEFAULT ''::text,
  "description"           text                     NOT NULL DEFAULT ''::text,
  "price_eur"             numeric                  NOT NULL,
  "compatibility"         text                     NOT NULL DEFAULT ''::text,
  "current_version"       text                     NOT NULL,
  "release_date"          date,
  "published"             boolean                  NOT NULL DEFAULT false,
  "also_included_in_text" text                     DEFAULT ''::text,
  "updated_at"            timestamp with time zone NOT NULL DEFAULT now(),
  "category_id"           bigint                   NOT NULL,
  "complexity_id"         bigint                   NOT NULL,
  CONSTRAINT "products_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."products"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."profiles" (
  "user_id"         uuid                     NOT NULL,
  "name"            text,
  "invoice_details" text,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"      timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "profiles_pkey" PRIMARY KEY (user_id)
);

ALTER TABLE "public"."profiles"
  ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON SEQUENCE "public"."categories_id_seq" FROM "anon";

REVOKE ALL ON SEQUENCE "public"."categories_id_seq" FROM "authenticated";

REVOKE ALL ON SEQUENCE "public"."categories_id_seq" FROM "service_role";

REVOKE ALL ON SEQUENCE "public"."complexities_id_seq" FROM "anon";

REVOKE ALL ON SEQUENCE "public"."complexities_id_seq" FROM "authenticated";

REVOKE ALL ON SEQUENCE "public"."complexities_id_seq" FROM "service_role";

REVOKE ALL ON SEQUENCE "public"."entitlements_id_seq" FROM "anon";

REVOKE ALL ON SEQUENCE "public"."entitlements_id_seq" FROM "authenticated";

REVOKE ALL ON SEQUENCE "public"."entitlements_id_seq" FROM "service_role";

REVOKE ALL ON SEQUENCE "public"."license_activations_id_seq" FROM "anon";

REVOKE ALL ON SEQUENCE "public"."license_activations_id_seq" FROM "authenticated";

REVOKE ALL ON SEQUENCE "public"."license_activations_id_seq" FROM "service_role";

REVOKE ALL ON SEQUENCE "public"."order_items_id_seq" FROM "anon";

REVOKE ALL ON SEQUENCE "public"."order_items_id_seq" FROM "authenticated";

REVOKE ALL ON SEQUENCE "public"."order_items_id_seq" FROM "service_role";

REVOKE ALL ON SEQUENCE "public"."orders_id_seq" FROM "anon";

REVOKE ALL ON SEQUENCE "public"."orders_id_seq" FROM "authenticated";

REVOKE ALL ON SEQUENCE "public"."orders_id_seq" FROM "service_role";

REVOKE ALL ON SEQUENCE "public"."product_media_id_seq" FROM "anon";

REVOKE ALL ON SEQUENCE "public"."product_media_id_seq" FROM "authenticated";

REVOKE ALL ON SEQUENCE "public"."product_media_id_seq" FROM "service_role";

REVOKE ALL ON SEQUENCE "public"."products_id_seq" FROM "anon";

REVOKE ALL ON SEQUENCE "public"."products_id_seq" FROM "authenticated";

REVOKE ALL ON SEQUENCE "public"."products_id_seq" FROM "service_role";

CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
begin
  insert into public.profiles (
    user_id
  )
  values (
    new.id
  )
  on conflict (user_id)
  do nothing;

  return new;
end;
$function$;

REVOKE ALL ON FUNCTION "public"."handle_new_user"() FROM "anon", "authenticated", "service_role";

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
  RETURNS event_trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog'
  AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

REVOKE ALL ON FUNCTION "public"."rls_auto_enable"() FROM "anon", "authenticated", "service_role";

CREATE OR REPLACE FUNCTION public.set_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

REVOKE ALL ON FUNCTION "public"."set_updated_at"() FROM "anon", "authenticated", "service_role";

ALTER TABLE "public"."admin_users"
  ADD CONSTRAINT "admin_users_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."entitlements"
  ADD CONSTRAINT "entitlements_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."license_activations"
  ADD CONSTRAINT "license_activations_entitlement_id_fkey" FOREIGN KEY (entitlement_id) REFERENCES public.entitlements(id) ON DELETE CASCADE;

ALTER TABLE "public"."license_activations"
  ADD CONSTRAINT "license_activations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."entitlements"
  ADD CONSTRAINT "entitlements_order_item_id_fkey" FOREIGN KEY (order_item_id) REFERENCES public.order_items(id) ON DELETE SET NULL;

ALTER TABLE "public"."order_items"
  ADD CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;

ALTER TABLE "public"."orders"
  ADD CONSTRAINT "orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE RESTRICT;

ALTER TABLE "public"."products"
  ADD CONSTRAINT "products_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.category(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "public"."products"
  ADD CONSTRAINT "products_complexity_id_fkey" FOREIGN KEY (complexity_id) REFERENCES public.complexity(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "public"."entitlements"
  ADD CONSTRAINT "entitlements_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "public"."license_activations"
  ADD CONSTRAINT "license_activations_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "public"."order_items"
  ADD CONSTRAINT "order_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "public"."product_media"
  ADD CONSTRAINT "product_media_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX entitlements_product_id_index ON public.entitlements USING btree (product_id);

CREATE INDEX entitlements_user_id_index ON public.entitlements USING btree (user_id);

CREATE INDEX license_activations_entitlement_id_index ON public.license_activations USING btree (entitlement_id);

CREATE UNIQUE INDEX license_activations_one_active_machine_per_entitlement ON public.license_activations USING btree (entitlement_id)
  WHERE (status = 'active'::text);

CREATE INDEX license_activations_product_id_index ON public.license_activations USING btree (product_id);

CREATE INDEX license_activations_user_id_index ON public.license_activations USING btree (user_id);

CREATE INDEX order_items_order_id_index ON public.order_items USING btree (order_id);

CREATE INDEX order_items_product_id_index ON public.order_items USING btree (product_id);

CREATE UNIQUE INDEX orders_provider_order_id_unique ON public.orders USING btree (provider_order_id)
  WHERE (provider_order_id IS NOT NULL);

CREATE UNIQUE INDEX orders_provider_transaction_id_unique ON public.orders USING btree (provider_transaction_id)
  WHERE (provider_transaction_id IS NOT NULL);

CREATE INDEX orders_user_id_index ON public.orders USING btree (user_id);

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

CREATE TRIGGER entitlements_set_updated_at
  BEFORE UPDATE ON public.entitlements
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER license_activations_set_updated_at
  BEFORE UPDATE ON public.license_activations
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER orders_set_updated_at
  BEFORE UPDATE ON public.orders
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER profiles_set_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE POLICY "admin users can read own membership" ON "public"."admin_users"
  FOR SELECT
  TO "authenticated"
  USING ((user_id = auth.uid()));

CREATE POLICY "Public can read active categories" ON "public"."category"
  FOR SELECT
  TO "anon", "authenticated"
  USING ((active = true));

CREATE POLICY "Public can read active complexities" ON "public"."complexity"
  FOR SELECT
  TO "anon", "authenticated"
  USING ((active = true));

CREATE POLICY "Users can read own entitlements" ON "public"."entitlements"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can read own license activations" ON "public"."license_activations"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can read own order items" ON "public"."order_items"
  FOR SELECT
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.orders
  WHERE ((orders.id = order_items.order_id) AND (orders.user_id = auth.uid())))));

CREATE POLICY "Users can read own orders" ON "public"."orders"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Public can read product media" ON "public"."product_media"
  FOR SELECT
  TO "anon", "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.products
  WHERE ((products.id = product_media.product_id) AND (products.published = true)))));

CREATE POLICY "Public can read published products" ON "public"."products"
  FOR SELECT
  TO "anon", "authenticated"
  USING ((published = true));

CREATE POLICY "Users can read own profile" ON "public"."profiles"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can update own profile" ON "public"."profiles"
  FOR UPDATE
  TO "authenticated"
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE EVENT TRIGGER "ensure_rls"
  ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  EXECUTE FUNCTION "public"."rls_auto_enable"();

GRANT EXECUTE ON FUNCTION "public"."handle_new_user"() TO PUBLIC;

REVOKE ALL ON FUNCTION "public"."handle_new_user"() FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."handle_new_user"() TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO PUBLIC;

REVOKE ALL ON FUNCTION "public"."rls_auto_enable"() FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."set_updated_at"() TO PUBLIC;

REVOKE ALL ON FUNCTION "public"."set_updated_at"() FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."set_updated_at"() TO "postgres";

REVOKE ALL ON TABLE "public"."admin_users" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."admin_users" TO "anon";

REVOKE ALL ON TABLE "public"."admin_users" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."admin_users" TO "authenticated";

REVOKE ALL ON TABLE "public"."admin_users" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."admin_users" TO "postgres";

REVOKE ALL ON TABLE "public"."admin_users" FROM "service_role";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."admin_users" TO "service_role";

REVOKE ALL ON TABLE "public"."category" FROM "anon";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."category" TO "anon";

REVOKE ALL ON TABLE "public"."category" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."category" TO "authenticated";

REVOKE ALL ON TABLE "public"."category" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."category" TO "postgres";

REVOKE ALL ON TABLE "public"."category" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."category" TO "service_role";

REVOKE ALL ON TABLE "public"."complexity" FROM "anon";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."complexity" TO "anon";

REVOKE ALL ON TABLE "public"."complexity" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."complexity" TO "authenticated";

REVOKE ALL ON TABLE "public"."complexity" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."complexity" TO "postgres";

REVOKE ALL ON TABLE "public"."complexity" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."complexity" TO "service_role";

REVOKE ALL ON TABLE "public"."entitlements" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."entitlements" TO "anon";

REVOKE ALL ON TABLE "public"."entitlements" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."entitlements" TO "authenticated";

REVOKE ALL ON TABLE "public"."entitlements" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."entitlements" TO "postgres";

REVOKE ALL ON TABLE "public"."entitlements" FROM "service_role";

GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."entitlements" TO "service_role";

REVOKE ALL ON TABLE "public"."license_activations" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."license_activations" TO "anon";

REVOKE ALL ON TABLE "public"."license_activations" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."license_activations" TO "authenticated";

REVOKE ALL ON TABLE "public"."license_activations" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."license_activations" TO "postgres";

REVOKE ALL ON TABLE "public"."license_activations" FROM "service_role";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."license_activations" TO "service_role";

REVOKE ALL ON TABLE "public"."order_items" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."order_items" TO "anon";

REVOKE ALL ON TABLE "public"."order_items" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."order_items" TO "authenticated";

REVOKE ALL ON TABLE "public"."order_items" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."order_items" TO "postgres";

REVOKE ALL ON TABLE "public"."order_items" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."order_items" TO "service_role";

REVOKE ALL ON TABLE "public"."orders" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."orders" TO "anon";

REVOKE ALL ON TABLE "public"."orders" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."orders" TO "authenticated";

REVOKE ALL ON TABLE "public"."orders" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."orders" TO "postgres";

REVOKE ALL ON TABLE "public"."orders" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."orders" TO "service_role";

REVOKE ALL ON TABLE "public"."product_media" FROM "anon";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."product_media" TO "anon";

REVOKE ALL ON TABLE "public"."product_media" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."product_media" TO "authenticated";

REVOKE ALL ON TABLE "public"."product_media" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."product_media" TO "postgres";

REVOKE ALL ON TABLE "public"."product_media" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."product_media" TO "service_role";

REVOKE ALL ON TABLE "public"."products" FROM "anon";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."products" TO "anon";

REVOKE ALL ON TABLE "public"."products" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."products" TO "authenticated";

REVOKE ALL ON TABLE "public"."products" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."products" TO "postgres";

REVOKE ALL ON TABLE "public"."products" FROM "service_role";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."products" TO "service_role";

REVOKE ALL ON TABLE "public"."profiles" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."profiles" TO "anon";

REVOKE ALL ON TABLE "public"."profiles" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "authenticated";

REVOKE ALL ON TABLE "public"."profiles" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "postgres";

REVOKE ALL ON TABLE "public"."profiles" FROM "service_role";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."profiles" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "service_role";

